ALTER TABLE [dbo].[Events] ADD CONSTRAINT [FKEY_EVEN_UNION] FOREIGN KEY ([UnionId]) REFERENCES [dbo].[Unions] ([UnionId]) ON DELETE NO ACTION ON UPDATE NO ACTION	

ALTER TABLE dbo.[Events] 
DROP CONSTRAINT CHK_FK_Event_To_League_Or_Club

ALTER TABLE dbo.[Events] 
ADD CONSTRAINT CHK_FK_Event_To_League_Or_Club_Or_Union
		CHECK ((LeagueId IS NULL AND ClubId IS NOT NULL AND UnionId IS NULL) 
			OR (LeagueId IS NOT NULL AND ClubId IS NULL AND UnionId IS NULL)
			OR (LeagueId IS NULL AND ClubId IS NULL AND UnionId IS NOT NULL))