ALTER TABLE UNIONS DROP COLUMN UnionFormTitle;

ALTER TABLE UNIONS DROP COLUMN UnionForm;


CREATE TABLE UnionForms 
(
	FormId INT PRIMARY KEY IDENTITY NOT NULL,
	UnionId INT NOT NULL,
	SeasonId INT NOT NULL,
	Title VARCHAR(50),
	FilePath VARCHAR(MAX),
	IsDeleted BIT NOT NULL DEFAULT 0,
	CONSTRAINT FK_UnionsForForms FOREIGN KEY (UnionId)
    REFERENCES Unions(UnionId),
	CONSTRAINT FK_SeasonsForForms FOREIGN KEY (SeasonId)
    REFERENCES Seasons(Id)
)
