//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מערכות.
        /// </summary>
        internal static string Acts {
            get {
                return ResourceManager.GetString("Acts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יחס מערכות.
        /// </summary>
        internal static string ActsRatio {
            get {
                return ResourceManager.GetString("ActsRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כתובת.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קטגוריה.
        /// </summary>
        internal static string Ages {
            get {
                return ResourceManager.GetString("Ages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ליגה א.
        /// </summary>
        internal static string AlefLeague {
            get {
                return ResourceManager.GetString("AlefLeague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ליגת על.
        /// </summary>
        internal static string AlLeague {
            get {
                return ResourceManager.GetString("AlLeague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בשעה.
        /// </summary>
        internal static string At {
            get {
                return ResourceManager.GetString("At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר חזה.
        /// </summary>
        internal static string AthleteNumber {
            get {
                return ResourceManager.GetString("AthleteNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to דירוג ליגת אתלטיקה.
        /// </summary>
        internal static string AthleticLeagueRanks {
            get {
                return ResourceManager.GetString("AthleticLeagueRanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ממוצע.
        /// </summary>
        internal static string AveragePoints {
            get {
                return ResourceManager.GetString("AveragePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מידע כללי.
        /// </summary>
        internal static string BasicInfo {
            get {
                return ResourceManager.GetString("BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יחס סלים.
        /// </summary>
        internal static string BasketRatio {
            get {
                return ResourceManager.GetString("BasketRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קרב שניים.
        /// </summary>
        internal static string BattleOfTwo {
            get {
                return ResourceManager.GetString("BattleOfTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך לידה.
        /// </summary>
        internal static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קטגוריה.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תוצאות קטגוריות.
        /// </summary>
        internal static string CategoryResults {
            get {
                return ResourceManager.GetString("CategoryResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סגור.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אגודה.
        /// </summary>
        internal static string Club {
            get {
                return ResourceManager.GetString("Club", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מועדון.
        /// </summary>
        internal static string ClubName {
            get {
                return ResourceManager.GetString("ClubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תחרות.
        /// </summary>
        internal static string Competition {
            get {
                return ResourceManager.GetString("Competition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם תחרות.
        /// </summary>
        internal static string CompetitionName {
            get {
                return ResourceManager.GetString("CompetitionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שיא אליפות.
        /// </summary>
        internal static string CompetitionRecord {
            get {
                return ResourceManager.GetString("CompetitionRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לוח תחרויות.
        /// </summary>
        internal static string CompetitionSchedule {
            get {
                return ResourceManager.GetString("CompetitionSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טבלת דירוג.
        /// </summary>
        internal static string CompetitionTable {
            get {
                return ResourceManager.GetString("CompetitionTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחזור.
        /// </summary>
        internal static string Cycle {
            get {
                return ResourceManager.GetString("Cycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תוקף ביטוח.
        /// </summary>
        internal static string DateOfInsuranceValidity {
            get {
                return ResourceManager.GetString("DateOfInsuranceValidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך/ שעה.
        /// </summary>
        internal static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יום.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תיאור.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rtl.
        /// </summary>
        internal static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מקצוע.
        /// </summary>
        internal static string Discipline {
            get {
                return ResourceManager.GetString("Discipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מקצועות.
        /// </summary>
        internal static string Disciplines {
            get {
                return ResourceManager.GetString("Disciplines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תיקו.
        /// </summary>
        internal static string Draw {
            get {
                return ResourceManager.GetString("Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נגמר.
        /// </summary>
        internal static string Ended {
            get {
                return ResourceManager.GetString("Ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כניסה.
        /// </summary>
        internal static string Entry {
            get {
                return ResourceManager.GetString("Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ארוע.
        /// </summary>
        internal static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טבלה מורחבת.
        /// </summary>
        internal static string ExtendedTable {
            get {
                return ResourceManager.GetString("ExtendedTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נקבה.
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מגרש.
        /// </summary>
        internal static string Field {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מרוצי שדה.
        /// </summary>
        internal static string FieldCompetition {
            get {
                return ResourceManager.GetString("FieldCompetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to דירוג מרוצי שדה.
        /// </summary>
        internal static string FieldRaceRanks {
            get {
                return ResourceManager.GetString("FieldRaceRanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תוצאה סופית.
        /// </summary>
        internal static string FinalResult {
            get {
                return ResourceManager.GetString("FinalResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to משעה.
        /// </summary>
        internal static string FromHour {
            get {
                return ResourceManager.GetString("FromHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם מלא.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טבלת הדירוג תוצג לאחר סיום כל המשחקים.
        /// </summary>
        internal static string FullRankingAlert {
            get {
                return ResourceManager.GetString("FullRankingAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מש.
        /// </summary>
        internal static string Game {
            get {
                return ResourceManager.GetString("Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to משחקים.
        /// </summary>
        internal static string Games {
            get {
                return ResourceManager.GetString("Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לוחות זמנים למשחק.
        /// </summary>
        internal static string GameSchedules {
            get {
                return ResourceManager.GetString("GameSchedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to משחקים.
        /// </summary>
        internal static string GamesNum {
            get {
                return ResourceManager.GetString("GamesNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to משחקונים.
        /// </summary>
        internal static string Gaming {
            get {
                return ResourceManager.GetString("Gaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מין.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יחס שערים.
        /// </summary>
        internal static string GoalRatio {
            get {
                return ResourceManager.GetString("GoalRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to גולדן ספייקס.
        /// </summary>
        internal static string GoldenSpikes {
            get {
                return ResourceManager.GetString("GoldenSpikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to גולדן ספייקס U-14.
        /// </summary>
        internal static string GoldenSpikesU14 {
            get {
                return ResourceManager.GetString("GoldenSpikesU14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to גולדן ספייקס U-16.
        /// </summary>
        internal static string GoldenSpikesU16 {
            get {
                return ResourceManager.GetString("GoldenSpikesU16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שחקן קבוצת חוץ.
        /// </summary>
        internal static string GuestPlayer {
            get {
                return ResourceManager.GetString("GuestPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ק. חוץ.
        /// </summary>
        internal static string GuestTeam {
            get {
                return ResourceManager.GetString("GuestTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קיים הפסד טכני.
        /// </summary>
        internal static string HasTechLost {
            get {
                return ResourceManager.GetString("HasTechLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קיים נצחון טכני.
        /// </summary>
        internal static string HasTechWin {
            get {
                return ResourceManager.GetString("HasTechWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מקצה.
        /// </summary>
        internal static string Heat {
            get {
                return ResourceManager.GetString("Heat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לוח מקצים.
        /// </summary>
        internal static string HeatsList {
            get {
                return ResourceManager.GetString("HeatsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שחקן קבוצת בית.
        /// </summary>
        internal static string HomePlayer {
            get {
                return ResourceManager.GetString("HomePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ק. בית.
        /// </summary>
        internal static string HomeTeam {
            get {
                return ResourceManager.GetString("HomeTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ת.ז.
        /// </summary>
        internal static string IdentNum {
            get {
                return ResourceManager.GetString("IdentNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to באולם.
        /// </summary>
        internal static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מידע.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לוח זמנים.
        /// </summary>
        internal static string InfoSchedule {
            get {
                return ResourceManager.GetString("InfoSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שיא ישראלי בינלאומי.
        /// </summary>
        internal static string IntentionalIsraeliRecord {
            get {
                return ResourceManager.GetString("IntentionalIsraeliRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עדיין לא נקבע.
        /// </summary>
        internal static string IsNotSetYet {
            get {
                return ResourceManager.GetString("IsNotSetYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שיא ישראלי.
        /// </summary>
        internal static string IsraeliRecord {
            get {
                return ResourceManager.GetString("IsraeliRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ליגת קדטים.
        /// </summary>
        internal static string KadeteLeague {
            get {
                return ResourceManager.GetString("KadeteLeague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שביל.
        /// </summary>
        internal static string Lane {
            get {
                return ResourceManager.GetString("Lane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to he.
        /// </summary>
        internal static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to על הליגה.
        /// </summary>
        internal static string LeagueAbout {
            get {
                return ResourceManager.GetString("LeagueAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to על הליגה.
        /// </summary>
        internal static string LeagueStructure {
            get {
                return ResourceManager.GetString("LeagueStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טבלת הליגה.
        /// </summary>
        internal static string League_LeagueRankedStandings {
            get {
                return ResourceManager.GetString("League_LeagueRankedStandings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טבלת דירוג.
        /// </summary>
        internal static string League_RankedStandings {
            get {
                return ResourceManager.GetString("League_RankedStandings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא הסתיימו כל המשחקים בשלב.
        /// </summary>
        internal static string League_RankedStanding_NoFinishedGamesInStage {
            get {
                return ResourceManager.GetString("League_RankedStanding_NoFinishedGamesInStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הנפה.
        /// </summary>
        internal static string Lifting {
            get {
                return ResourceManager.GetString("Lifting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הפסדים.
        /// </summary>
        internal static string LossNum {
            get {
                return ResourceManager.GetString("LossNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הפ.
        /// </summary>
        internal static string Lost {
            get {
                return ResourceManager.GetString("Lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to זכר.
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to משחקים.
        /// </summary>
        internal static string Matches {
            get {
                return ResourceManager.GetString("Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to גברים.
        /// </summary>
        internal static string Men {
            get {
                return ResourceManager.GetString("Men", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חודש.
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קרב רב.
        /// </summary>
        internal static string MultiBattle {
            get {
                return ResourceManager.GetString("MultiBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ליגה ארצית.
        /// </summary>
        internal static string NationalLeague {
            get {
                return ResourceManager.GetString("NationalLeague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הבא.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אין תחרויות.
        /// </summary>
        internal static string NoActiveCompetitions {
            get {
                return ResourceManager.GetString("NoActiveCompetitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ללא.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סדר עליה.
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סדר.
        /// </summary>
        internal static string OrderRaw {
            get {
                return ResourceManager.GetString("OrderRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עונש.
        /// </summary>
        internal static string Penalty {
            get {
                return ResourceManager.GetString("Penalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טלפון.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מיקום.
        /// </summary>
        internal static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שחקן.
        /// </summary>
        internal static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ניקוד.
        /// </summary>
        internal static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יחס נקודות.
        /// </summary>
        internal static string PointsRatio {
            get {
                return ResourceManager.GetString("PointsRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נק.
        /// </summary>
        internal static string PointsShort {
            get {
                return ResourceManager.GetString("PointsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ניקוד לממוצע.
        /// </summary>
        internal static string PointsToAverage {
            get {
                return ResourceManager.GetString("PointsToAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ליגה לאומית.
        /// </summary>
        internal static string PremiereLeague {
            get {
                return ResourceManager.GetString("PremiereLeague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קודם.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הדפס.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to דחיקה.
        /// </summary>
        internal static string Pushing {
            get {
                return ResourceManager.GetString("Pushing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        internal static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מיקום.
        /// </summary>
        internal static string RankRaw {
            get {
                return ResourceManager.GetString("RankRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שיא.
        /// </summary>
        internal static string Record {
            get {
                return ResourceManager.GetString("Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שיאים.
        /// </summary>
        internal static string Records {
            get {
                return ResourceManager.GetString("Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נרשמים.
        /// </summary>
        internal static string Registrations {
            get {
                return ResourceManager.GetString("Registrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נרשמים לכל המקצים.
        /// </summary>
        internal static string RegistrationToAllHeats {
            get {
                return ResourceManager.GetString("RegistrationToAllHeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נרשמים למקצה.
        /// </summary>
        internal static string RegistrationToHeat {
            get {
                return ResourceManager.GetString("RegistrationToHeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תוצאה.
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תוצאת.
        /// </summary>
        internal static string ResultOf {
            get {
                return ResourceManager.GetString("ResultOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תוצאות.
        /// </summary>
        internal static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תוצאות לפי אגודה.
        /// </summary>
        internal static string ResultsByClub {
            get {
                return ResourceManager.GetString("ResultsByClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תוצאות מקצים.
        /// </summary>
        internal static string ResultsByHeat {
            get {
                return ResourceManager.GetString("ResultsByHeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מרוצי כביש.
        /// </summary>
        internal static string RoadCompetition {
            get {
                return ResourceManager.GetString("RoadCompetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הקפות.
        /// </summary>
        internal static string Runs {
            get {
                return ResourceManager.GetString("Runs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לוח משחקים ותוצאות.
        /// </summary>
        internal static string ScheduleResults {
            get {
                return ResourceManager.GetString("ScheduleResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תוצאות.
        /// </summary>
        internal static string Scores {
            get {
                return ResourceManager.GetString("Scores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שיאים עונתיים.
        /// </summary>
        internal static string SeasonalBests {
            get {
                return ResourceManager.GetString("SeasonalBests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תוצאת שנה.
        /// </summary>
        internal static string SeasonRecord {
            get {
                return ResourceManager.GetString("SeasonRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מע.
        /// </summary>
        internal static string Set {
            get {
                return ResourceManager.GetString("Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מערכות.
        /// </summary>
        internal static string Sets {
            get {
                return ResourceManager.GetString("Sets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ספורטאים.
        /// </summary>
        internal static string Sportsmans {
            get {
                return ResourceManager.GetString("Sportsmans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מס ספורטאים.
        /// </summary>
        internal static string SportsmenNumber {
            get {
                return ResourceManager.GetString("SportsmenNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תחרויות אצטדיון.
        /// </summary>
        internal static string StadiumCompetition {
            get {
                return ResourceManager.GetString("StadiumCompetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך התחלה.
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to התחיל.
        /// </summary>
        internal static string Started {
            get {
                return ResourceManager.GetString("Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שעת התחלה.
        /// </summary>
        internal static string StartHour {
            get {
                return ResourceManager.GetString("StartHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start list.
        /// </summary>
        internal static string StartList {
            get {
                return ResourceManager.GetString("StartList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רשימת משתתפים.
        /// </summary>
        internal static string StartListHeb {
            get {
                return ResourceManager.GetString("StartListHeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סטטוס.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קבוצה.
        /// </summary>
        internal static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מנהל קבוצה.
        /// </summary>
        internal static string TeamManager {
            get {
                return ResourceManager.GetString("TeamManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם קבוצה.
        /// </summary>
        internal static string TeamName {
            get {
                return ResourceManager.GetString("TeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טכני.
        /// </summary>
        internal static string TechLossesNum {
            get {
                return ResourceManager.GetString("TechLossesNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נצחון טכני.
        /// </summary>
        internal static string TechWin {
            get {
                return ResourceManager.GetString("TechWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תוקף אייטניס.
        /// </summary>
        internal static string TenicardValidity {
            get {
                return ResourceManager.GetString("TenicardValidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תיקו.
        /// </summary>
        internal static string Tie {
            get {
                return ResourceManager.GetString("Tie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לתחרות.
        /// </summary>
        internal static string ToCompetition {
            get {
                return ResourceManager.GetString("ToCompetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to היום.
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to למשחק.
        /// </summary>
        internal static string ToGame {
            get {
                return ResourceManager.GetString("ToGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לשעה.
        /// </summary>
        internal static string ToHour {
            get {
                return ResourceManager.GetString("ToHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סה&quot;כ.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סה&quot;כ משתתפים.
        /// </summary>
        internal static string TotalParticipants {
            get {
                return ResourceManager.GetString("TotalParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סה&quot;כ נרשמים.
        /// </summary>
        internal static string TotalRegistrations {
            get {
                return ResourceManager.GetString("TotalRegistrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תוקף אישור רפואי.
        /// </summary>
        internal static string ValidityOfMedicalExamination {
            get {
                return ResourceManager.GetString("ValidityOfMedicalExamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בהמתנה.
        /// </summary>
        internal static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שבוע.
        /// </summary>
        internal static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to משקל.
        /// </summary>
        internal static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הצהרת משקל להרמה.
        /// </summary>
        internal static string WeightDeclaration {
            get {
                return ResourceManager.GetString("WeightDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שקילה.
        /// </summary>
        internal static string WeightIn {
            get {
                return ResourceManager.GetString("WeightIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שעות שקילה.
        /// </summary>
        internal static string WeightTime {
            get {
                return ResourceManager.GetString("WeightTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נצ.
        /// </summary>
        internal static string Win {
            get {
                return ResourceManager.GetString("Win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רוח.
        /// </summary>
        internal static string Wind {
            get {
                return ResourceManager.GetString("Wind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ניצחונות.
        /// </summary>
        internal static string WinsNum {
            get {
                return ResourceManager.GetString("WinsNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נשים.
        /// </summary>
        internal static string Women {
            get {
                return ResourceManager.GetString("Women", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שנת לידה.
        /// </summary>
        internal static string YearOfBirth {
            get {
                return ResourceManager.GetString("YearOfBirth", resourceCulture);
            }
        }
    }
}
