//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityForm
    {
        public ActivityForm()
        {
            this.ActivityFormsDetails = new HashSet<ActivityFormsDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ActivityId { get; set; }
        public bool IsPublished { get; set; }
        public Nullable<int> PublishedBy { get; set; }
        public Nullable<System.DateTime> DatePublished { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public int UpdatedBy { get; set; }
        public string ImageFile { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<ActivityFormsDetail> ActivityFormsDetails { get; set; }
    }
}
