//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityBranch
    {
        public ActivityBranch()
        {
            this.Activities = new HashSet<Activity>();
            this.ActivityBranchesStates = new HashSet<ActivityBranchesState>();
        }
    
        public int AtivityBranchId { get; set; }
        public string BranchName { get; set; }
        public Nullable<int> SeasonId { get; set; }
        public Nullable<int> UnionId { get; set; }
        public Nullable<int> ClubId { get; set; }
    
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual Season Season { get; set; }
        public virtual Union Union { get; set; }
        public virtual ICollection<ActivityBranchesState> ActivityBranchesStates { get; set; }
    }
}
