//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityFormsFile
    {
        public int Id { get; set; }
        public Nullable<int> ActivityId { get; set; }
        public string PropertyName { get; set; }
        public string FileName { get; set; }
    
        public virtual Activity Activity { get; set; }
    }
}
