//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public Activity()
        {
            this.ActivitiesLeagues = new HashSet<ActivitiesLeague>();
            this.ActivitiesPrices = new HashSet<ActivitiesPrice>();
            this.ActivitiesUsers = new HashSet<ActivitiesUser>();
            this.ActivityCustomPrices = new HashSet<ActivityCustomPrice>();
            this.ActivityForms = new HashSet<ActivityForm>();
            this.ActivityFormsFiles = new HashSet<ActivityFormsFile>();
            this.ActivityFormsSubmittedDatas = new HashSet<ActivityFormsSubmittedData>();
            this.ActivityStatusColumnsVisibilities = new HashSet<ActivityStatusColumnsVisibility>();
            this.ActivityStatusColumnNames = new HashSet<ActivityStatusColumnName>();
            this.ActivityStatusColumnsOrders = new HashSet<ActivityStatusColumnsOrder>();
            this.ActivityStatusColumnsSortings = new HashSet<ActivityStatusColumnsSorting>();
        }
    
        public int ActivityId { get; set; }
        public bool IsPublished { get; set; }
        public System.DateTime Date { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string PaymentDescription { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string FormPayment { get; set; }
        public bool ByBenefactor { get; set; }
        public bool AttachDocuments { get; set; }
        public bool MedicalCertificate { get; set; }
        public bool InsuranceCertificate { get; set; }
        public Nullable<int> UnionId { get; set; }
        public Nullable<int> SeasonId { get; set; }
        public int ActivityBranchId { get; set; }
        public Nullable<bool> IsAutomatic { get; set; }
        public Nullable<decimal> SecondTeamDiscount { get; set; }
        public bool SecondTeamNoInsurance { get; set; }
        public Nullable<int> ClubId { get; set; }
        public bool RestrictLeagues { get; set; }
        public string RestrictedLeagues { get; set; }
        public bool RegistrationPrice { get; set; }
        public bool InsurancePrice { get; set; }
        public bool MembersFee { get; set; }
        public bool AllowNoInsurancePayment { get; set; }
        public bool AllowNoFeePayment { get; set; }
        public bool HandlingFee { get; set; }
        public bool AllowNoHandlingFeePayment { get; set; }
        public bool NoPriceOnBuiltInRegistration { get; set; }
        public bool ParticipationPrice { get; set; }
        public bool CustomPricesEnabled { get; set; }
        public bool NoTeamRegistration { get; set; }
        public bool AllowNewTeamRegistration { get; set; }
        public Nullable<decimal> UnionApprovedPlayerDiscount { get; set; }
        public bool UnionApprovedPlayerNoInsurance { get; set; }
        public Nullable<decimal> EscortDiscount { get; set; }
        public bool EscortNoInsurance { get; set; }
        public bool AllowEscortRegistration { get; set; }
        public bool RestrictCustomPricesToOneItem { get; set; }
        public bool ShowOnlyApprovedTeams { get; set; }
        public bool DisableRegPaymentForExistingClubs { get; set; }
        public bool RegisterToTrainingTeamsOnly { get; set; }
        public bool AllowNoCustomPricesSelected { get; set; }
        public bool CreateClubTeam { get; set; }
        public bool RestrictSchools { get; set; }
        public string RestrictedSchools { get; set; }
        public bool AllowCompetitiveMembers { get; set; }
        public int RegistrationForMembers { get; set; }
        public bool AllowOnlyApprovedMembers { get; set; }
        public bool DoNotAllowDuplicateRegistrations { get; set; }
        public bool OnlyApprovedClubs { get; set; }
        public bool AllowNoParticipationPayment { get; set; }
        public string DefaultLanguage { get; set; }
        public bool RestrictGenders { get; set; }
        public bool CheckCompetitionAge { get; set; }
        public bool ClubLeagueTeamsOnly { get; set; }
        public bool PostponeParticipationPayment { get; set; }
        public bool RestrictGendersByTeam { get; set; }
        public bool MultiTeamRegistrations { get; set; }
        public string RedirectLinkOnSuccess { get; set; }
        public bool RestrictTeams { get; set; }
        public string RestrictedTeams { get; set; }
        public bool MovePlayerToTeam { get; set; }
        public bool AdjustRegistrationPriceByDate { get; set; }
        public bool AdjustParticipationPriceByDate { get; set; }
        public bool AdjustInsurancePriceByDate { get; set; }
        public bool EnableBrotherDiscount { get; set; }
        public decimal BrotherDiscountAmount { get; set; }
        public bool BrotherDiscountInPercent { get; set; }
        public bool RestrictLeaguesByAge { get; set; }
        public bool AllowNoRegistrationPayment { get; set; }
        public bool AllowToEnterDateToAdjustPrices { get; set; }
        public int PaymentMethod { get; set; }
        public bool ForbidToChangeNameForExistingPlayers { get; set; }
        public bool RegistrationsByCompetitionsCategory { get; set; }
    
        public virtual ActivityBranch ActivityBranch { get; set; }
        public virtual Club Club { get; set; }
        public virtual Season Season { get; set; }
        public virtual Union Union { get; set; }
        public virtual ICollection<ActivitiesLeague> ActivitiesLeagues { get; set; }
        public virtual ICollection<ActivitiesPrice> ActivitiesPrices { get; set; }
        public virtual ICollection<ActivitiesUser> ActivitiesUsers { get; set; }
        public virtual ICollection<ActivityCustomPrice> ActivityCustomPrices { get; set; }
        public virtual ICollection<ActivityForm> ActivityForms { get; set; }
        public virtual ICollection<ActivityFormsFile> ActivityFormsFiles { get; set; }
        public virtual ICollection<ActivityFormsSubmittedData> ActivityFormsSubmittedDatas { get; set; }
        public virtual ICollection<ActivityStatusColumnsVisibility> ActivityStatusColumnsVisibilities { get; set; }
        public virtual ICollection<ActivityStatusColumnName> ActivityStatusColumnNames { get; set; }
        public virtual ICollection<ActivityStatusColumnsOrder> ActivityStatusColumnsOrders { get; set; }
        public virtual ICollection<ActivityStatusColumnsSorting> ActivityStatusColumnsSortings { get; set; }
    }
}
