//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityFormsSubmittedData
    {
        public int Id { get; set; }
        public Nullable<int> ActivityId { get; set; }
        public int PlayerId { get; set; }
        public Nullable<int> TeamId { get; set; }
        public Nullable<int> LeagueId { get; set; }
        public string NameForInvoice { get; set; }
        public bool IsPaymentByBenefactor { get; set; }
        public string PaymentByBenefactor { get; set; }
        public string Document { get; set; }
        public string MedicalCert { get; set; }
        public string InsuranceCert { get; set; }
        public string Comments { get; set; }
        public bool SelfInsurance { get; set; }
        public System.DateTime DateSubmitted { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.Guid> CardComLpc { get; set; }
        public bool CardComPaymentCompleted { get; set; }
        public Nullable<System.DateTime> CardComPaymentDate { get; set; }
        public decimal Paid { get; set; }
        public string UnionComment { get; set; }
        public decimal InsurancePaid { get; set; }
        public string CustomFields { get; set; }
        public decimal RegistrationPrice { get; set; }
        public decimal InsurancePrice { get; set; }
        public decimal RegistrationPaid { get; set; }
        public Nullable<int> ClubId { get; set; }
        public decimal ParticipationPrice { get; set; }
        public string ClubComment { get; set; }
        public decimal ParticipationPaid { get; set; }
        public decimal MembersFee { get; set; }
        public decimal MembersFeePaid { get; set; }
        public bool DisableMembersFeePayment { get; set; }
        public bool DisableInsurancePayment { get; set; }
        public decimal HandlingFee { get; set; }
        public decimal HandlingFeePaid { get; set; }
        public bool DisableHandlingFeePayment { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string CustomPrices { get; set; }
        public decimal TenicardPrice { get; set; }
        public decimal TenicardPaid { get; set; }
        public bool IsSchoolInsurance { get; set; }
        public bool DoNotPayTenicardPrice { get; set; }
        public bool DisableParticipationPayment { get; set; }
        public bool PostponeParticipationPayment { get; set; }
        public string RegistrationCardComProductId { get; set; }
        public string InsuranceCardComProductId { get; set; }
        public string ParticipationCardComProductId { get; set; }
        public string MembersFeeCardComProductId { get; set; }
        public string HandlingFeeCardComProductId { get; set; }
        public string TenicardCardComProductId { get; set; }
        public Nullable<System.Guid> LiqPayOrderId { get; set; }
        public bool LiqPayPaymentCompleted { get; set; }
        public Nullable<System.DateTime> LiqPayPaymentDate { get; set; }
        public Nullable<int> CardComNumberOfPayments { get; set; }
        public Nullable<int> CardComInvoiceNumber { get; set; }
        public Nullable<int> BrotherUserId { get; set; }
        public Nullable<int> PreviousClubId { get; set; }
        public Nullable<bool> IsSeenByClubManager { get; set; }
        public bool DisableRegistrationPayment { get; set; }
        public Nullable<System.DateTime> PlayerStartDate { get; set; }
        public Nullable<System.Guid> PayPalLogLigId { get; set; }
        public string PayPalPaymentId { get; set; }
        public string PayPalPayerId { get; set; }
        public Nullable<int> CompetitionDisciplineId { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Club Club { get; set; }
        public virtual League League { get; set; }
        public virtual Team Team { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Club Club1 { get; set; }
        public virtual CompetitionDiscipline CompetitionDiscipline { get; set; }
    }
}
