//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvBanner
    {
        public int id { get; set; }
        public int count { get; set; }
        public string linkurl { get; set; }
        public string image { get; set; }
        public Nullable<int> leagueId { get; set; }
        public Nullable<int> clubId { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual Union Union { get; set; }
    }
}
