//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AthleteNumber
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int SeasonId { get; set; }
        public Nullable<int> AthleteNumber1 { get; set; }
        public bool IsAthleteNumberProduced { get; set; }
    
        public virtual Season Season { get; set; }
        public virtual User User { get; set; }
    }
}
