//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AthleticLeague
    {
        public AthleticLeague()
        {
            this.Leagues = new HashSet<League>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int SeasonId { get; set; }
        public string AlLeague { get; set; }
        public string PremiereLeague { get; set; }
        public string NationalLeague { get; set; }
        public string AlefLeague { get; set; }
        public string AlLeagueF { get; set; }
        public string PremiereLeagueF { get; set; }
        public string NationalLeagueF { get; set; }
        public string AlefLeagueF { get; set; }
        public bool IsAdultLeague { get; set; }
    
        public virtual Season Season { get; set; }
        public virtual ICollection<League> Leagues { get; set; }
    }
}
