//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditorium
    {
        public Auditorium()
        {
            this.TeamsAuditoriums = new HashSet<TeamsAuditorium>();
            this.GamesCycles = new HashSet<GamesCycle>();
            this.ClubTrainingDays = new HashSet<ClubTrainingDay>();
            this.TeamTrainings = new HashSet<TeamTraining>();
            this.TennisGameCycles = new HashSet<TennisGameCycle>();
            this.Leagues = new HashSet<League>();
            this.Users = new HashSet<User>();
        }
    
        public int AuditoriumId { get; set; }
        public Nullable<int> UnionId { get; set; }
        public string Name { get; set; }
        public bool IsArchive { get; set; }
        public string Address { get; set; }
        public Nullable<int> SeasonId { get; set; }
        public Nullable<int> ClubId { get; set; }
        public Nullable<int> LanesNumber { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<int> DisciplineId { get; set; }
        public bool IsHeated { get; set; }
        public bool IsIndoor { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual Season Season { get; set; }
        public virtual Union Union { get; set; }
        public virtual ICollection<TeamsAuditorium> TeamsAuditoriums { get; set; }
        public virtual ICollection<GamesCycle> GamesCycles { get; set; }
        public virtual ICollection<ClubTrainingDay> ClubTrainingDays { get; set; }
        public virtual ICollection<TeamTraining> TeamTrainings { get; set; }
        public virtual ICollection<TennisGameCycle> TennisGameCycles { get; set; }
        public virtual ICollection<League> Leagues { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual Discipline Discipline { get; set; }
    }
}
