//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BicycleFriendshipPayment
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public Nullable<int> ClubId { get; set; }
        public int TeamId { get; set; }
        public decimal FriendshipPrice { get; set; }
        public decimal ChipPrice { get; set; }
        public decimal UciPrice { get; set; }
        public System.Guid LogLigPaymentId { get; set; }
        public Nullable<long> OfficeGuyCustomerId { get; set; }
        public Nullable<long> OfficeGuyPaymentId { get; set; }
        public Nullable<int> OfficeGuyDocumentNumber { get; set; }
        public bool IsPaid { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DatePaid { get; set; }
        public Nullable<int> SeasonId { get; set; }
        public bool Discarded { get; set; }
        public Nullable<int> DiscardedBy { get; set; }
        public Nullable<System.DateTime> DiscardDate { get; set; }
        public string Comment { get; set; }
        public bool IsManual { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual Team Team { get; set; }
        public virtual User User { get; set; }
        public virtual Season Season { get; set; }
        public virtual User DiscardUser { get; set; }
        public virtual User CreatedByUser { get; set; }
    }
}
