//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BicycleCompetitionDiscipline
    {
        public BicycleCompetitionDiscipline()
        {
            this.DisciplineExpertises = new HashSet<DisciplineExpertise>();
            this.Leagues = new HashSet<League>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> SeasonId { get; set; }
        public Nullable<int> UnionId { get; set; }
    
        public virtual Season Season { get; set; }
        public virtual Union Union { get; set; }
        public virtual ICollection<DisciplineExpertise> DisciplineExpertises { get; set; }
        public virtual ICollection<League> Leagues { get; set; }
    }
}
