//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BicycleDisciplineRegistration
    {
        public int Id { get; set; }
        public Nullable<int> CompetitionExpertiesHeatId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> IsArchive { get; set; }
        public Nullable<int> ClubId { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual CompetitionExpertiesHeat CompetitionExpertiesHeat { get; set; }
        public virtual User User { get; set; }
    }
}
