//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardComIndicator
    {
        public int Id { get; set; }
        public System.Guid LowProfileCode { get; set; }
        public int TerminalNumber { get; set; }
        public int Operation { get; set; }
        public Nullable<int> ActivityId { get; set; }
        public string ApiUserName { get; set; }
        public string CardComIndicatorInfo { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
