//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriesPlaceDate
    {
        public int Id { get; set; }
        public int TeamId { get; set; }
        public Nullable<System.DateTime> QualificationStartDate { get; set; }
        public Nullable<System.DateTime> QualificationEndDate { get; set; }
        public Nullable<System.DateTime> FinalStartDate { get; set; }
        public Nullable<System.DateTime> FinalEndDate { get; set; }
    
        public virtual Team Team { get; set; }
    }
}
