//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClubTraining
    {
        public ClubTraining()
        {
            this.ClubTrainingAttendances = new HashSet<ClubTrainingAttendance>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public int TeamId { get; set; }
        public Nullable<int> AuditoriumId { get; set; }
        public System.DateTime TrainingDate { get; set; }
        public string Content { get; set; }
        public bool IsPublished { get; set; }
    
        public virtual Auditorium Auditorium { get; set; }
        public virtual ICollection<ClubTrainingAttendance> ClubTrainingAttendances { get; set; }
        public virtual Team Team { get; set; }
    }
}
