//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Club
    {
        public Club()
        {
            this.Seasons = new HashSet<Season>();
            this.TeamStandingGames = new HashSet<TeamStandingGame>();
            this.Auditoriums = new HashSet<Auditorium>();
            this.Events = new HashSet<Event>();
            this.Leagues = new HashSet<League>();
            this.SentMessages = new HashSet<SentMessage>();
            this.ClubTrainingDays = new HashSet<ClubTrainingDay>();
            this.Schools = new HashSet<School>();
            this.ClubTeamPrices = new HashSet<ClubTeamPrice>();
            this.PlayerDiscounts = new HashSet<PlayerDiscount>();
            this.Clubs1 = new HashSet<Club>();
            this.TeamsPlayers = new HashSet<TeamsPlayer>();
            this.UsersJobs = new HashSet<UsersJob>();
            this.DistanceTables = new HashSet<DistanceTable>();
            this.PlayerDisciplines = new HashSet<PlayerDiscipline>();
            this.ClubDisciplines = new HashSet<ClubDiscipline>();
            this.TeamDisciplines = new HashSet<TeamDiscipline>();
            this.Activities = new HashSet<Activity>();
            this.ActivityFormsSubmittedDatas = new HashSet<ActivityFormsSubmittedData>();
            this.CompetitionRegistrations = new HashSet<CompetitionRegistration>();
            this.AdditionalGymnastics = new HashSet<AdditionalGymnastic>();
            this.AdditionalTeamGymnastics = new HashSet<AdditionalTeamGymnastic>();
            this.UsersJobs1 = new HashSet<UsersJob>();
            this.TeamRegistrations = new HashSet<TeamRegistration>();
            this.RefereeRegistrations = new HashSet<RefereeRegistration>();
            this.SportsRegistrations = new HashSet<SportsRegistration>();
            this.AdvBanners = new HashSet<AdvBanner>();
            this.ClubTeams = new HashSet<ClubTeam>();
            this.ClubTeams1 = new HashSet<ClubTeam>();
            this.ClubPayments = new HashSet<ClubPayment>();
            this.ClubBalances = new HashSet<ClubBalance>();
            this.CompetitionDisciplineRegistrations = new HashSet<CompetitionDisciplineRegistration>();
            this.CompetitionRouteClubs = new HashSet<CompetitionRouteClub>();
            this.CompetitionTeamRouteClubs = new HashSet<CompetitionTeamRouteClub>();
            this.CompetitionClubsCorrections = new HashSet<CompetitionClubsCorrection>();
            this.CompetitionDisciplineTeams = new HashSet<CompetitionDisciplineTeam>();
            this.CompetitionDisciplineClubsRegistrations = new HashSet<CompetitionDisciplineClubsRegistration>();
            this.ActivityFormsSubmittedDatas1 = new HashSet<ActivityFormsSubmittedData>();
            this.BicycleFriendshipPayments = new HashSet<BicycleFriendshipPayment>();
            this.BicycleDisciplineRegistrations = new HashSet<BicycleDisciplineRegistration>();
        }
    
        public int ClubId { get; set; }
        public Nullable<int> SectionId { get; set; }
        public string Name { get; set; }
        public bool IsArchive { get; set; }
        public string Logo { get; set; }
        public string PrimaryImage { get; set; }
        public string Description { get; set; }
        public string IndexImage { get; set; }
        public string IndexAbout { get; set; }
        public string TermsCondition { get; set; }
        public string ContactPhone { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UnionId { get; set; }
        public Nullable<bool> IsSectionClub { get; set; }
        public Nullable<bool> IsUnionClub { get; set; }
        public Nullable<int> SportCenterId { get; set; }
        public string NGO_Number { get; set; }
        public Nullable<int> SeasonId { get; set; }
        public bool IsClubFeesPaid { get; set; }
        public bool IsClubManagerCanSeePayReport { get; set; }
        public Nullable<int> SportType { get; set; }
        public bool IsTrainingEnabled { get; set; }
        public string MedicalSertificateFile { get; set; }
        public Nullable<int> ParentClubId { get; set; }
        public Nullable<int> SportSectionId { get; set; }
        public Nullable<int> ClubNumber { get; set; }
        public Nullable<System.DateTime> DateOfClubApproval { get; set; }
        public string CertificateOfIncorporation { get; set; }
        public string ApprovalOfInsuranceCover { get; set; }
        public string AuthorizedSignatories { get; set; }
        public Nullable<bool> IsCertificateApproved { get; set; }
        public Nullable<bool> IsInsuranceCoverApproved { get; set; }
        public Nullable<bool> IsAuthorizedSignatoriesApproved { get; set; }
        public bool IsReportsEnabled { get; set; }
        public string DistanceSettings { get; set; }
        public bool StatementApproved { get; set; }
        public int NumberOfCourts { get; set; }
        public string ReportSettings { get; set; }
        public bool IsFlowerOfSport { get; set; }
        public string ClubInsurance { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> IsClubApproved { get; set; }
        public Nullable<System.DateTime> InitialDateOfClubApproval { get; set; }
        public bool ReportRemoveTravelDistance { get; set; }
        public bool IsClubApproveByRegional { get; set; }
        public Nullable<System.DateTime> DateOfClubApprovalByRegional { get; set; }
        public Nullable<int> RegionalId { get; set; }
        public string ClubDisplayName { get; set; }
        public string AuthorizedSignPersonName { get; set; }
        public Nullable<bool> SignEachSeparately { get; set; }
        public Nullable<bool> SignTogether { get; set; }
        public string ForeignName { get; set; }
        public bool IsUnionArchive { get; set; }
        public bool IsNationalTeam { get; set; }
        public Nullable<int> AccountingKeyNumber { get; set; }
    
        public virtual Section Section { get; set; }
        public virtual Union Union { get; set; }
        public virtual ICollection<Season> Seasons { get; set; }
        public virtual SportCenter SportCenter { get; set; }
        public virtual ICollection<TeamStandingGame> TeamStandingGames { get; set; }
        public virtual ICollection<Auditorium> Auditoriums { get; set; }
        public virtual ICollection<Event> Events { get; set; }
        public virtual Sport Sport { get; set; }
        public virtual ICollection<League> Leagues { get; set; }
        public virtual ICollection<SentMessage> SentMessages { get; set; }
        public virtual ICollection<ClubTrainingDay> ClubTrainingDays { get; set; }
        public virtual ICollection<School> Schools { get; set; }
        public virtual ICollection<ClubTeamPrice> ClubTeamPrices { get; set; }
        public virtual ICollection<PlayerDiscount> PlayerDiscounts { get; set; }
        public virtual ICollection<Club> Clubs1 { get; set; }
        public virtual Club Club1 { get; set; }
        public virtual Section Section1 { get; set; }
        public virtual ICollection<TeamsPlayer> TeamsPlayers { get; set; }
        public virtual ICollection<UsersJob> UsersJobs { get; set; }
        public virtual ICollection<DistanceTable> DistanceTables { get; set; }
        public virtual ICollection<PlayerDiscipline> PlayerDisciplines { get; set; }
        public virtual ICollection<ClubDiscipline> ClubDisciplines { get; set; }
        public virtual ICollection<TeamDiscipline> TeamDisciplines { get; set; }
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual ICollection<ActivityFormsSubmittedData> ActivityFormsSubmittedDatas { get; set; }
        public virtual ICollection<CompetitionRegistration> CompetitionRegistrations { get; set; }
        public virtual ICollection<AdditionalGymnastic> AdditionalGymnastics { get; set; }
        public virtual ICollection<AdditionalTeamGymnastic> AdditionalTeamGymnastics { get; set; }
        public virtual ICollection<UsersJob> UsersJobs1 { get; set; }
        public virtual ICollection<TeamRegistration> TeamRegistrations { get; set; }
        public virtual ICollection<RefereeRegistration> RefereeRegistrations { get; set; }
        public virtual ICollection<SportsRegistration> SportsRegistrations { get; set; }
        public virtual ICollection<AdvBanner> AdvBanners { get; set; }
        public virtual ICollection<ClubTeam> ClubTeams { get; set; }
        public virtual ICollection<ClubTeam> ClubTeams1 { get; set; }
        public virtual ICollection<ClubPayment> ClubPayments { get; set; }
        public virtual ICollection<ClubBalance> ClubBalances { get; set; }
        public virtual ICollection<CompetitionDisciplineRegistration> CompetitionDisciplineRegistrations { get; set; }
        public virtual ICollection<CompetitionRouteClub> CompetitionRouteClubs { get; set; }
        public virtual ICollection<CompetitionTeamRouteClub> CompetitionTeamRouteClubs { get; set; }
        public virtual ICollection<CompetitionClubsCorrection> CompetitionClubsCorrections { get; set; }
        public virtual Regional Regional { get; set; }
        public virtual ICollection<CompetitionDisciplineTeam> CompetitionDisciplineTeams { get; set; }
        public virtual ICollection<CompetitionDisciplineClubsRegistration> CompetitionDisciplineClubsRegistrations { get; set; }
        public virtual ICollection<ActivityFormsSubmittedData> ActivityFormsSubmittedDatas1 { get; set; }
        public virtual ICollection<BicycleFriendshipPayment> BicycleFriendshipPayments { get; set; }
        public virtual ICollection<BicycleDisciplineRegistration> BicycleDisciplineRegistrations { get; set; }
    }
}
