//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClubBalance
    {
        public ClubBalance()
        {
            this.TeamRegistrationPayments = new HashSet<TeamRegistrationPayment>();
            this.TeamPlayersPayments = new HashSet<TeamPlayersPayment>();
        }
    
        public int Id { get; set; }
        public int ClubId { get; set; }
        public int ActionUserId { get; set; }
        public Nullable<decimal> Income { get; set; }
        public Nullable<decimal> Expense { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> IsPdfReport { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<int> SeasonId { get; set; }
        public Nullable<int> LeagueId { get; set; }
        public Nullable<System.DateTime> TimeOfAction { get; set; }
        public Nullable<int> Reference { get; set; }
    
        public virtual User User { get; set; }
        public virtual Club Club { get; set; }
        public virtual ICollection<TeamRegistrationPayment> TeamRegistrationPayments { get; set; }
        public virtual ICollection<TeamPlayersPayment> TeamPlayersPayments { get; set; }
        public virtual Season Season { get; set; }
    }
}
