//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClubPayment
    {
        public int Id { get; set; }
        public int ClubId { get; set; }
        public decimal Paid { get; set; }
        public System.DateTime DateOfPayment { get; set; }
    
        public virtual Club Club { get; set; }
    }
}
