//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetitionAge
    {
        public CompetitionAge()
        {
            this.Teams = new HashSet<Team>();
            this.TennisRanks = new HashSet<TennisRank>();
            this.CompetitionDisciplines = new HashSet<CompetitionDiscipline>();
            this.CompetitionExpertiesHeatsAges = new HashSet<CompetitionExpertiesHeatsAge>();
        }
    
        public int id { get; set; }
        public string age_name { get; set; }
        public Nullable<System.DateTime> from_birth { get; set; }
        public Nullable<System.DateTime> to_birth { get; set; }
        public Nullable<int> UnionId { get; set; }
        public Nullable<int> SeasonId { get; set; }
        public Nullable<int> gender { get; set; }
        public Nullable<decimal> from_weight { get; set; }
        public Nullable<decimal> to_weight { get; set; }
        public Nullable<int> DisciplineId { get; set; }
        public Nullable<int> FriendshipTypeId { get; set; }
        public Nullable<int> AverageAge { get; set; }
        public Nullable<int> from_age { get; set; }
        public Nullable<int> to_age { get; set; }
        public Nullable<bool> IsUCICategory { get; set; }
        public Nullable<bool> IsMix { get; set; }
        public Nullable<bool> IsIsraelChampionship { get; set; }
        public Nullable<bool> IsHidden { get; set; }
        public string age_foreign_name { get; set; }
    
        public virtual ICollection<Team> Teams { get; set; }
        public virtual Gender Gender1 { get; set; }
        public virtual Season Season { get; set; }
        public virtual Union Union { get; set; }
        public virtual ICollection<TennisRank> TennisRanks { get; set; }
        public virtual ICollection<CompetitionDiscipline> CompetitionDisciplines { get; set; }
        public virtual Discipline Discipline { get; set; }
        public virtual FriendshipsType FriendshipsType { get; set; }
        public virtual ICollection<CompetitionExpertiesHeatsAge> CompetitionExpertiesHeatsAges { get; set; }
    }
}
