//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetitionResult
    {
        public int Id { get; set; }
        public int CompetitionRegistrationId { get; set; }
        public string Heat { get; set; }
        public Nullable<int> Lane { get; set; }
        public string Result { get; set; }
        public Nullable<double> Wind { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<long> SortValue { get; set; }
        public int AlternativeResult { get; set; }
        public Nullable<int> Lifting1 { get; set; }
        public Nullable<int> Lifting2 { get; set; }
        public Nullable<int> Lifting3 { get; set; }
        public Nullable<decimal> ClubPoints { get; set; }
        public Nullable<int> Push1 { get; set; }
        public Nullable<int> Push2 { get; set; }
        public Nullable<int> Push3 { get; set; }
        public Nullable<int> Lift1Success { get; set; }
        public Nullable<int> Lift2Success { get; set; }
        public Nullable<int> Lift3Success { get; set; }
        public Nullable<int> Push1Success { get; set; }
        public Nullable<int> Push2Success { get; set; }
        public Nullable<int> Push3Success { get; set; }
        public Nullable<int> PushResult { get; set; }
        public Nullable<int> LiftingResult { get; set; }
        public Nullable<int> FinalResult { get; set; }
        public Nullable<int> CombinedPoint { get; set; }
        public Nullable<bool> IsPointsAddedToClub { get; set; }
        public string Attempt1 { get; set; }
        public Nullable<int> Alternative1 { get; set; }
        public string Attempt2 { get; set; }
        public Nullable<int> Alternative2 { get; set; }
        public string Attempt3 { get; set; }
        public Nullable<int> Alternative3 { get; set; }
        public string Attempt4 { get; set; }
        public Nullable<int> Alternative4 { get; set; }
        public string Attempt5 { get; set; }
        public Nullable<int> Alternative5 { get; set; }
        public string Attempt6 { get; set; }
        public Nullable<int> Alternative6 { get; set; }
        public string Records { get; set; }
        public Nullable<int> LiveSplitOrder { get; set; }
        public Nullable<double> Attempt1Wind { get; set; }
        public Nullable<double> Attempt2Wind { get; set; }
        public Nullable<double> Attempt3Wind { get; set; }
        public Nullable<double> Attempt4Wind { get; set; }
        public Nullable<double> Attempt5Wind { get; set; }
        public Nullable<double> Attempt6Wind { get; set; }
        public string CustomFields { get; set; }
    }
}
