//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetitionExpertiesHeat
    {
        public CompetitionExpertiesHeat()
        {
            this.CompetitionExpertiesDisciplineHeats = new HashSet<CompetitionExpertiesDisciplineHeat>();
            this.BicycleDisciplineRegistrations = new HashSet<BicycleDisciplineRegistration>();
            this.CompetitionExpertiesHeatsAges = new HashSet<CompetitionExpertiesHeatsAge>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CompetitionExpertiesId { get; set; }
        public Nullable<int> BicycleCompetitionHeatId { get; set; }
        public Nullable<int> CompetitionLevelId { get; set; }
    
        public virtual BicycleCompetitionHeat BicycleCompetitionHeat { get; set; }
        public virtual CompetitionExperty CompetitionExperty { get; set; }
        public virtual ICollection<CompetitionExpertiesDisciplineHeat> CompetitionExpertiesDisciplineHeats { get; set; }
        public virtual ICollection<BicycleDisciplineRegistration> BicycleDisciplineRegistrations { get; set; }
        public virtual CompetitionLevel CompetitionLevel { get; set; }
        public virtual ICollection<CompetitionExpertiesHeatsAge> CompetitionExpertiesHeatsAges { get; set; }
    }
}
