//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetitionDisciplineHeatStartTime
    {
        public int Id { get; set; }
        public int CompetitionDisciplineId { get; set; }
        public string HeatName { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<bool> IsFinal { get; set; }
    
        public virtual CompetitionDiscipline CompetitionDiscipline { get; set; }
    }
}
