//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetitionExpertiesDisciplineHeat
    {
        public int Id { get; set; }
        public Nullable<int> CompetitionExpertiesHeatId { get; set; }
        public Nullable<int> HeatDisciplineId { get; set; }
    
        public virtual CompetitionExpertiesHeat CompetitionExpertiesHeat { get; set; }
        public virtual Discipline Discipline { get; set; }
    }
}
