//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetitionExperty
    {
        public CompetitionExperty()
        {
            this.CompetitionExpertiesHeats = new HashSet<CompetitionExpertiesHeat>();
        }
    
        public int Id { get; set; }
        public Nullable<int> DisciplineExpertiseId { get; set; }
        public Nullable<int> CompetitionId { get; set; }
    
        public virtual DisciplineExpertise DisciplineExpertise { get; set; }
        public virtual League League { get; set; }
        public virtual ICollection<CompetitionExpertiesHeat> CompetitionExpertiesHeats { get; set; }
    }
}
