//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetitionTeamRouteClub
    {
        public int Id { get; set; }
        public int CompetitionTeamRouteId { get; set; }
        public int ClubId { get; set; }
        public Nullable<int> MaximumRegistrationsAllowed { get; set; }
    }
}
