//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetitionDisciplineTeam
    {
        public CompetitionDisciplineTeam()
        {
            this.CompetitionDisciplineRegistrations = new HashSet<CompetitionDisciplineRegistration>();
        }
    
        public int Id { get; set; }
        public int ClubId { get; set; }
        public int CompetitionDisciplineId { get; set; }
        public Nullable<int> TeamNumber { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual CompetitionDiscipline CompetitionDiscipline { get; set; }
        public virtual ICollection<CompetitionDisciplineRegistration> CompetitionDisciplineRegistrations { get; set; }
    }
}
