//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetitionClubsCorrection
    {
        public int Id { get; set; }
        public int LeagueId { get; set; }
        public int SeasonId { get; set; }
        public int ClubId { get; set; }
        public int GenderId { get; set; }
        public decimal Correction { get; set; }
        public Nullable<decimal> Points { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> ResultsCounted { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual League League { get; set; }
        public virtual Season Season { get; set; }
    }
}
