//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetitionRegion
    {
        public CompetitionRegion()
        {
            this.Teams = new HashSet<Team>();
        }
    
        public int id { get; set; }
        public string region_name { get; set; }
        public Nullable<int> UnionId { get; set; }
        public Nullable<int> SeasonId { get; set; }
    
        public virtual ICollection<Team> Teams { get; set; }
        public virtual Season Season { get; set; }
        public virtual Union Union { get; set; }
    }
}
