//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetitionDisciplineRegistration
    {
        public CompetitionDisciplineRegistration()
        {
            this.CompetitionResult = new HashSet<CompetitionResult>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public int CompetitionDisciplineId { get; set; }
        public bool IsArchive { get; set; }
        public Nullable<int> ClubId { get; set; }
        public Nullable<decimal> WeightDeclaration { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsCharged { get; set; }
        public Nullable<int> WeightliftingSessionId { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<bool> Presence { get; set; }
        public Nullable<int> CompetitionDisciplineTeamId { get; set; }
        public Nullable<bool> IsCoxwain { get; set; }
        public string Result { get; set; }
        public Nullable<int> Rank { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual CompetitionDiscipline CompetitionDiscipline { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<CompetitionResult> CompetitionResult { get; set; }
        public virtual WeightLiftingSession WeightLiftingSession { get; set; }
        public virtual CompetitionDisciplineTeam CompetitionDisciplineTeam { get; set; }
    }
}
