//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DaysForHosting
    {
        public DaysForHosting()
        {
            this.TeamHostingDays = new HashSet<TeamHostingDay>();
        }
    
        public int Id { get; set; }
        public int LeagueId { get; set; }
        public int SeasonId { get; set; }
        public int Day { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
    
        public virtual League League { get; set; }
        public virtual Season Season { get; set; }
        public virtual ICollection<TeamHostingDay> TeamHostingDays { get; set; }
    }
}
