//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisciplineExpertise
    {
        public DisciplineExpertise()
        {
            this.CompetitionExperties = new HashSet<CompetitionExperty>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> BicycleCompetitionDisciplineId { get; set; }
    
        public virtual BicycleCompetitionDiscipline BicycleCompetitionDiscipline { get; set; }
        public virtual ICollection<CompetitionExperty> CompetitionExperties { get; set; }
    }
}
