//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discipline
    {
        public Discipline()
        {
            this.UsersJobs = new HashSet<UsersJob>();
            this.DisciplinesDocs = new HashSet<DisciplinesDoc>();
            this.Leagues = new HashSet<League>();
            this.SentMessages = new HashSet<SentMessage>();
            this.DisciplineRoutes = new HashSet<DisciplineRoute>();
            this.PlayerDisciplines = new HashSet<PlayerDiscipline>();
            this.ClubDisciplines = new HashSet<ClubDiscipline>();
            this.TeamDisciplines = new HashSet<TeamDiscipline>();
            this.CompetitionRoutes = new HashSet<CompetitionRoute>();
            this.CompetitionTeamRoutes = new HashSet<CompetitionTeamRoute>();
            this.Instruments = new HashSet<Instrument>();
            this.DisciplineTeamRoutes = new HashSet<DisciplineTeamRoute>();
            this.CompetitionAges = new HashSet<CompetitionAge>();
            this.Auditoriums = new HashSet<Auditorium>();
            this.TeamsPlayers = new HashSet<TeamsPlayer>();
            this.TeamsPlayers1 = new HashSet<TeamsPlayer>();
            this.CompetitionExpertiesDisciplineHeats = new HashSet<CompetitionExpertiesDisciplineHeat>();
        }
    
        public int DisciplineId { get; set; }
        public int UnionId { get; set; }
        public string Name { get; set; }
        public bool IsArchive { get; set; }
        public string Logo { get; set; }
        public string PrimaryImage { get; set; }
        public string Description { get; set; }
        public string IndexImage { get; set; }
        public string IndexAbout { get; set; }
        public string TermsCondition { get; set; }
        public Nullable<int> Format { get; set; }
        public bool IsPreffered { get; set; }
        public Nullable<int> Class { get; set; }
        public string DisciplineType { get; set; }
        public Nullable<int> NumberOfSportsmen { get; set; }
        public Nullable<bool> RoadHeat { get; set; }
        public Nullable<bool> MountainHeat { get; set; }
        public Nullable<bool> Coxwain { get; set; }
    
        public virtual Union Union { get; set; }
        public virtual ICollection<UsersJob> UsersJobs { get; set; }
        public virtual ICollection<DisciplinesDoc> DisciplinesDocs { get; set; }
        public virtual ICollection<League> Leagues { get; set; }
        public virtual ICollection<SentMessage> SentMessages { get; set; }
        public virtual ICollection<DisciplineRoute> DisciplineRoutes { get; set; }
        public virtual ICollection<PlayerDiscipline> PlayerDisciplines { get; set; }
        public virtual ICollection<ClubDiscipline> ClubDisciplines { get; set; }
        public virtual ICollection<TeamDiscipline> TeamDisciplines { get; set; }
        public virtual ICollection<CompetitionRoute> CompetitionRoutes { get; set; }
        public virtual ICollection<CompetitionTeamRoute> CompetitionTeamRoutes { get; set; }
        public virtual ICollection<Instrument> Instruments { get; set; }
        public virtual ICollection<DisciplineTeamRoute> DisciplineTeamRoutes { get; set; }
        public virtual ICollection<CompetitionAge> CompetitionAges { get; set; }
        public virtual ICollection<Auditorium> Auditoriums { get; set; }
        public virtual ICollection<TeamsPlayer> TeamsPlayers { get; set; }
        public virtual ICollection<TeamsPlayer> TeamsPlayers1 { get; set; }
        public virtual ICollection<CompetitionExpertiesDisciplineHeat> CompetitionExpertiesDisciplineHeats { get; set; }
    }
}
