//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisciplineRecord
    {
        public DisciplineRecord()
        {
            this.SeasonRecords = new HashSet<SeasonRecord>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Format { get; set; }
        public string Categories { get; set; }
        public string IntentionalIsraeliRecord { get; set; }
        public string IsraeliRecord { get; set; }
        public Nullable<long> IntentionalIsraeliRecordSortValue { get; set; }
        public Nullable<long> IsraeliRecordSortValue { get; set; }
        public int UnionId { get; set; }
        public string Disciplines { get; set; }
    
        public virtual Union Union { get; set; }
        public virtual ICollection<SeasonRecord> SeasonRecords { get; set; }
    }
}
