//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisciplineRoute
    {
        public DisciplineRoute()
        {
            this.UsersRoutes = new HashSet<UsersRoute>();
            this.CompetitionRoutes = new HashSet<CompetitionRoute>();
            this.TeamsRoutes = new HashSet<TeamsRoute>();
            this.RouteRanks = new HashSet<RouteRank>();
        }
    
        public int Id { get; set; }
        public int DisciplineId { get; set; }
        public string Route { get; set; }
        public Nullable<int> Hierarchy { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual ICollection<UsersRoute> UsersRoutes { get; set; }
        public virtual ICollection<CompetitionRoute> CompetitionRoutes { get; set; }
        public virtual ICollection<TeamsRoute> TeamsRoutes { get; set; }
        public virtual ICollection<RouteRank> RouteRanks { get; set; }
    }
}
