//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistanceTable
    {
        public int Id { get; set; }
        public Nullable<int> UnionId { get; set; }
        public Nullable<int> ClubId { get; set; }
        public string CityFromName { get; set; }
        public string CityToName { get; set; }
        public Nullable<int> Distance { get; set; }
        public string DistanceType { get; set; }
        public Nullable<int> SeasonId { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual Union Union { get; set; }
        public virtual Season Season { get; set; }
    }
}
