//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverDetail
    {
        public DriverDetail()
        {
            this.Vehicles = new HashSet<Vehicle>();
        }
    
        public int Id { get; set; }
        public int SportsmanId { get; set; }
        public System.DateTime OwnerShipDate { get; set; }
        public System.DateTime IssueDate { get; set; }
        public int NumberOfPreviousOwners { get; set; }
    
        public virtual TeamsPlayer TeamsPlayer { get; set; }
        public virtual ICollection<Vehicle> Vehicles { get; set; }
    }
}
