//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameStatistic
    {
        public long Id { get; set; }
        public int GameId { get; set; }
        public int PlayerId { get; set; }
        public Nullable<long> MinutesPlayed { get; set; }
        public Nullable<int> FG { get; set; }
        public Nullable<int> FGA { get; set; }
        public Nullable<int> ThreePT { get; set; }
        public Nullable<int> ThreePA { get; set; }
        public Nullable<int> TwoPT { get; set; }
        public Nullable<int> TwoPA { get; set; }
        public Nullable<int> FT { get; set; }
        public Nullable<int> FTA { get; set; }
        public Nullable<int> OREB { get; set; }
        public Nullable<int> DREB { get; set; }
        public Nullable<int> REB { get; set; }
        public Nullable<int> TOT { get; set; }
        public Nullable<int> AST { get; set; }
        public Nullable<int> STL { get; set; }
        public Nullable<int> BLK { get; set; }
        public Nullable<int> TO { get; set; }
        public Nullable<int> BS { get; set; }
        public Nullable<int> PF { get; set; }
        public Nullable<int> PTS { get; set; }
        public Nullable<double> EFF { get; set; }
        public Nullable<double> DIFF { get; set; }
        public Nullable<int> FGM { get; set; }
        public Nullable<int> FTM { get; set; }
        public Nullable<int> TeamId { get; set; }
    
        public virtual GamesCycle GamesCycle { get; set; }
        public virtual TeamsPlayer TeamsPlayer { get; set; }
        public virtual Team Team { get; set; }
    }
}
