//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GamesCycle
    {
        public GamesCycle()
        {
            this.GameSets = new HashSet<GameSet>();
            this.NotesGames = new HashSet<NotesGame>();
            this.WallThreads = new HashSet<WallThread>();
            this.Users = new HashSet<User>();
            this.Statistics = new HashSet<Statistic>();
            this.GameStatistics = new HashSet<GameStatistic>();
            this.TennisLeagueGames = new HashSet<TennisLeagueGame>();
            this.OfficialGameReportDetails = new HashSet<OfficialGameReportDetail>();
            this.WaterpoloStatistics = new HashSet<WaterpoloStatistic>();
        }
    
        public int CycleId { get; set; }
        public int StageId { get; set; }
        public int CycleNum { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<int> AuditoriumId { get; set; }
        public Nullable<int> GuestTeamId { get; set; }
        public int GuestTeamScore { get; set; }
        public Nullable<int> HomeTeamId { get; set; }
        public int HomeTeamScore { get; set; }
        public string RefereeIds { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string GameStatus { get; set; }
        public Nullable<int> TechnicalWinnnerId { get; set; }
        public Nullable<int> MaxPlayoffPos { get; set; }
        public Nullable<int> MinPlayoffPos { get; set; }
        public Nullable<int> BracketId { get; set; }
        public bool IsPublished { get; set; }
        public Nullable<int> BracketIndex { get; set; }
        public Nullable<int> GuestTeamPos { get; set; }
        public Nullable<int> HomeTeamPos { get; set; }
        public Nullable<int> HomeAthleteId { get; set; }
        public Nullable<int> GuestAthleteId { get; set; }
        public string SpectatorIds { get; set; }
        public string DeskIds { get; set; }
        public string PdfGameReport { get; set; }
        public string Note { get; set; }
        public bool IsDateUpdated { get; set; }
        public Nullable<int> RoundNum { get; set; }
        public bool IsNotSetYet { get; set; }
        public string Remark { get; set; }
        public string ReportFileName { get; set; }
        public Nullable<int> AppliedExclusionId { get; set; }
    
        public virtual Auditorium Auditorium { get; set; }
        public virtual Group Group { get; set; }
        public virtual PlayoffBracket PlayoffBracket { get; set; }
        public virtual ICollection<GameSet> GameSets { get; set; }
        public virtual ICollection<NotesGame> NotesGames { get; set; }
        public virtual ICollection<WallThread> WallThreads { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual Team GuestTeam { get; set; }
        public virtual Team HomeTeam { get; set; }
        public virtual TeamsPlayer TeamsPlayer { get; set; }
        public virtual TeamsPlayer TeamsPlayer1 { get; set; }
        public virtual ICollection<Statistic> Statistics { get; set; }
        public virtual ICollection<GameStatistic> GameStatistics { get; set; }
        public virtual ICollection<TennisLeagueGame> TennisLeagueGames { get; set; }
        public virtual ICollection<OfficialGameReportDetail> OfficialGameReportDetails { get; set; }
        public virtual Stage Stage { get; set; }
        public virtual ICollection<WaterpoloStatistic> WaterpoloStatistics { get; set; }
        public virtual PenaltyForExclusion PenaltyForExclusion { get; set; }
    }
}
