//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instrument
    {
        public Instrument()
        {
            this.CompetitionRegistrations = new HashSet<CompetitionRegistration>();
        }
    
        public int Id { get; set; }
        public int DisciplineId { get; set; }
        public int SeasonId { get; set; }
        public string Name { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual Season Season { get; set; }
        public virtual ICollection<CompetitionRegistration> CompetitionRegistrations { get; set; }
    }
}
