//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class KarateUnionPayment
    {
        public KarateUnionPayment()
        {
            this.DisplayedPaymentMessages = new HashSet<DisplayedPaymentMessage>();
        }
    
        public int Id { get; set; }
        public int UnionId { get; set; }
        public int SeasonId { get; set; }
        public Nullable<int> FromNumber { get; set; }
        public Nullable<int> ToNumber { get; set; }
        public Nullable<decimal> Price { get; set; }
        public bool IsShown { get; set; }
    
        public virtual Season Season { get; set; }
        public virtual Union Union { get; set; }
        public virtual ICollection<DisplayedPaymentMessage> DisplayedPaymentMessages { get; set; }
    }
}
