//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeagueOfficialsSetting
    {
        public int Id { get; set; }
        public int LeagueId { get; set; }
        public int JobsRolesId { get; set; }
        public Nullable<decimal> PaymentPerGame { get; set; }
        public int PaymentPerGameCurrency { get; set; }
        public Nullable<decimal> PaymentTravel { get; set; }
        public int TravelMetricType { get; set; }
        public int TravelPaymentCurrencyType { get; set; }
        public Nullable<decimal> RateAPerGame { get; set; }
        public Nullable<decimal> RateBPerGame { get; set; }
        public Nullable<decimal> RateAForTravel { get; set; }
        public Nullable<decimal> RateBForTravel { get; set; }
        public Nullable<decimal> RateCPerGame { get; set; }
        public Nullable<decimal> RateCForTravel { get; set; }
    
        public virtual JobsRole JobsRole { get; set; }
        public virtual League League { get; set; }
    }
}
