//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class League
    {
        public League()
        {
            this.Events = new HashSet<Event>();
            this.Games = new HashSet<Game>();
            this.LeaguesDocs = new HashSet<LeaguesDoc>();
            this.LeaguesPrices = new HashSet<LeaguesPrice>();
            this.LeagueTeams = new HashSet<LeagueTeams>();
            this.TeamsFans = new HashSet<TeamsFan>();
            this.UsersJobs = new HashSet<UsersJob>();
            this.SentMessages = new HashSet<SentMessage>();
            this.WeightLiftingSessions = new HashSet<WeightLiftingSession>();
            this.PlayersBenefactorPrices = new HashSet<PlayersBenefactorPrice>();
            this.PlayerDiscounts = new HashSet<PlayerDiscount>();
            this.MemberFees = new HashSet<MemberFee>();
            this.HandlingFees = new HashSet<HandlingFee>();
            this.LeagueOfficialsSettings = new HashSet<LeagueOfficialsSetting>();
            this.TeamsPlayers = new HashSet<TeamsPlayer>();
            this.ActivitiesLeagues = new HashSet<ActivitiesLeague>();
            this.ActivityFormsSubmittedDatas = new HashSet<ActivityFormsSubmittedData>();
            this.CompetitionRoutes = new HashSet<CompetitionRoute>();
            this.CompetitionTeamRoutes = new HashSet<CompetitionTeamRoute>();
            this.CompetitionRegistrations = new HashSet<CompetitionRegistration>();
            this.AdditionalGymnastics = new HashSet<AdditionalGymnastic>();
            this.AdditionalTeamGymnastics = new HashSet<AdditionalTeamGymnastic>();
            this.TeamRegistrations = new HashSet<TeamRegistration>();
            this.PositionSettings = new HashSet<PositionSetting>();
            this.RefereeRegistrations = new HashSet<RefereeRegistration>();
            this.SportsRegistrations = new HashSet<SportsRegistration>();
            this.DaysForHostings = new HashSet<DaysForHosting>();
            this.LeagueScheduleStates = new HashSet<LeagueScheduleState>();
            this.LevelDateSettings = new HashSet<LevelDateSetting>();
            this.LeaguesFans = new HashSet<LeaguesFan>();
            this.Leagues1 = new HashSet<League>();
            this.CompetitionDisciplines = new HashSet<CompetitionDiscipline>();
            this.RankedStandingCorrections = new HashSet<RankedStandingCorrection>();
            this.Stages = new HashSet<Stage>();
            this.CompetitionClubsCorrections = new HashSet<CompetitionClubsCorrection>();
            this.RefereeCompetitionRegistrations = new HashSet<RefereeCompetitionRegistration>();
            this.TennisCategoryPlayoffRanks = new HashSet<TennisCategoryPlayoffRank>();
            this.CompetitionExperties = new HashSet<CompetitionExperty>();
        }
    
        public int LeagueId { get; set; }
        public Nullable<int> UnionId { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> AgeId { get; set; }
        public string Name { get; set; }
        public string Logo { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        public string Terms { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsArchive { get; set; }
        public bool IsCompetitionLeague { get; set; }
        public Nullable<int> Place { get; set; }
        public Nullable<bool> EilatTournament { get; set; }
        public short SortOrder { get; set; }
        public Nullable<int> SeasonId { get; set; }
        public Nullable<int> ClubId { get; set; }
        public decimal MaximumHandicapScoreValue { get; set; }
        public string AboutLeague { get; set; }
        public string LeagueStructure { get; set; }
        public Nullable<decimal> TeamRegistrationPrice { get; set; }
        public Nullable<decimal> PlayerRegistrationPrice { get; set; }
        public Nullable<decimal> PlayerInsurancePrice { get; set; }
        public Nullable<System.DateTime> MaximumAge { get; set; }
        public Nullable<System.DateTime> MinimumAge { get; set; }
        public Nullable<int> MinimumPlayersTeam { get; set; }
        public Nullable<int> MaximumPlayersTeam { get; set; }
        public string LeagueCode { get; set; }
        public Nullable<int> DisciplineId { get; set; }
        public Nullable<System.DateTime> LeagueStartDate { get; set; }
        public Nullable<System.DateTime> LeagueEndDate { get; set; }
        public Nullable<System.DateTime> EndRegistrationDate { get; set; }
        public Nullable<System.DateTime> EndTeamRegistrationDate { get; set; }
        public string AllowedCLubsIds { get; set; }
        public Nullable<double> FiveHandicapReduction { get; set; }
        public bool IsPositionSettingsEnabled { get; set; }
        public bool IsTeam { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> MinParticipationReq { get; set; }
        public string PlaceOfCompetition { get; set; }
        public Nullable<System.DateTime> StartRegistrationDate { get; set; }
        public string RegistrationLink { get; set; }
        public Nullable<int> DuplicatedLeagueId { get; set; }
        public Nullable<int> MaxRegistrations { get; set; }
        public Nullable<int> CompetitionAuditoriumId { get; set; }
        public Nullable<int> AthleticLeagueId { get; set; }
        public bool IsFieldCompetition { get; set; }
        public bool IsDailyCompetition { get; set; }
        public Nullable<System.DateTime> StartTeamRegistrationDate { get; set; }
        public Nullable<int> MaxParticipationAllowedForSportsman { get; set; }
        public Nullable<bool> IsSeniorCompetition { get; set; }
        public int IsClubCompetition { get; set; }
        public Nullable<bool> NoTeamRegistration { get; set; }
        public Nullable<int> BicycleCompetitionDisciplineId { get; set; }
        public Nullable<int> LevelId { get; set; }
        public int CompetitionType { get; set; }
        public bool IsMastersCompetition { get; set; }
    
        public virtual Age Age { get; set; }
        public virtual Club Club { get; set; }
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<Game> Games { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Season Season { get; set; }
        public virtual Union Union { get; set; }
        public virtual ICollection<LeaguesDoc> LeaguesDocs { get; set; }
        public virtual ICollection<LeaguesPrice> LeaguesPrices { get; set; }
        public virtual ICollection<LeagueTeams> LeagueTeams { get; set; }
        public virtual ICollection<TeamsFan> TeamsFans { get; set; }
        public virtual ICollection<UsersJob> UsersJobs { get; set; }
        public virtual ICollection<SentMessage> SentMessages { get; set; }
        public virtual ICollection<WeightLiftingSession> WeightLiftingSessions { get; set; }
        public virtual Discipline Discipline { get; set; }
        public virtual ICollection<PlayersBenefactorPrice> PlayersBenefactorPrices { get; set; }
        public virtual ICollection<PlayerDiscount> PlayerDiscounts { get; set; }
        public virtual ICollection<MemberFee> MemberFees { get; set; }
        public virtual ICollection<HandlingFee> HandlingFees { get; set; }
        public virtual ICollection<LeagueOfficialsSetting> LeagueOfficialsSettings { get; set; }
        public virtual ICollection<TeamsPlayer> TeamsPlayers { get; set; }
        public virtual ICollection<ActivitiesLeague> ActivitiesLeagues { get; set; }
        public virtual ICollection<ActivityFormsSubmittedData> ActivityFormsSubmittedDatas { get; set; }
        public virtual ICollection<CompetitionRoute> CompetitionRoutes { get; set; }
        public virtual ICollection<CompetitionTeamRoute> CompetitionTeamRoutes { get; set; }
        public virtual ICollection<CompetitionRegistration> CompetitionRegistrations { get; set; }
        public virtual ICollection<AdditionalGymnastic> AdditionalGymnastics { get; set; }
        public virtual ICollection<AdditionalTeamGymnastic> AdditionalTeamGymnastics { get; set; }
        public virtual ICollection<TeamRegistration> TeamRegistrations { get; set; }
        public virtual ICollection<PositionSetting> PositionSettings { get; set; }
        public virtual ICollection<RefereeRegistration> RefereeRegistrations { get; set; }
        public virtual ICollection<SportsRegistration> SportsRegistrations { get; set; }
        public virtual ICollection<DaysForHosting> DaysForHostings { get; set; }
        public virtual ICollection<LeagueScheduleState> LeagueScheduleStates { get; set; }
        public virtual ICollection<LevelDateSetting> LevelDateSettings { get; set; }
        public virtual ICollection<LeaguesFan> LeaguesFans { get; set; }
        public virtual ICollection<League> Leagues1 { get; set; }
        public virtual League League1 { get; set; }
        public virtual ICollection<CompetitionDiscipline> CompetitionDisciplines { get; set; }
        public virtual ICollection<RankedStandingCorrection> RankedStandingCorrections { get; set; }
        public virtual ICollection<Stage> Stages { get; set; }
        public virtual ICollection<CompetitionClubsCorrection> CompetitionClubsCorrections { get; set; }
        public virtual ICollection<RefereeCompetitionRegistration> RefereeCompetitionRegistrations { get; set; }
        public virtual Auditorium Auditorium { get; set; }
        public virtual AthleticLeague AthleticLeague { get; set; }
        public virtual ICollection<TennisCategoryPlayoffRank> TennisCategoryPlayoffRanks { get; set; }
        public virtual BicycleCompetitionDiscipline BicycleCompetitionDiscipline { get; set; }
        public virtual CompetitionLevel CompetitionLevel { get; set; }
        public virtual ICollection<CompetitionExperty> CompetitionExperties { get; set; }
    }
}
