//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LevelPointsSetting
    {
        public int Id { get; set; }
        public int LevelId { get; set; }
        public int SeasonId { get; set; }
        public int Rank { get; set; }
        public int Points { get; set; }
        public Nullable<int> PointsForPairs { get; set; }
    
        public virtual CompetitionLevel CompetitionLevel { get; set; }
        public virtual Season Season { get; set; }
    }
}
