//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalInstitute
    {
        public MedicalInstitute()
        {
            this.TeamsPlayers = new HashSet<TeamsPlayer>();
        }
    
        public int MedicalInstitutesId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public int SeasonId { get; set; }
        public int UnionId { get; set; }
    
        public virtual Season Season { get; set; }
        public virtual Union Union { get; set; }
        public virtual ICollection<TeamsPlayer> TeamsPlayers { get; set; }
    }
}
