//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotesMessage
    {
        public NotesMessage()
        {
            this.NotesRecipients = new HashSet<NotesRecipient>();
            this.Teams = new HashSet<Team>();
            this.SentMessages = new HashSet<SentMessage>();
            this.Childs = new HashSet<NotesMessage>();
            this.NotesAttachedFiles = new HashSet<NotesAttachedFile>();
        }
    
        public int MsgId { get; set; }
        public string Message { get; set; }
        public int TypeId { get; set; }
        public System.DateTime SendDate { get; set; }
        public bool SentByEmail { get; set; }
        public string img { get; set; }
        public string video { get; set; }
        public Nullable<int> parent { get; set; }
        public Nullable<int> Sender { get; set; }
        public bool SentForClubManagers { get; set; }
        public string Subject { get; set; }
        public Nullable<bool> SentForTeamManagers { get; set; }
    
        public virtual ICollection<NotesRecipient> NotesRecipients { get; set; }
        public virtual ICollection<Team> Teams { get; set; }
        public virtual ICollection<SentMessage> SentMessages { get; set; }
        public virtual ICollection<NotesMessage> Childs { get; set; }
        public virtual NotesMessage NotesMessage1 { get; set; }
        public virtual User SendUser { get; set; }
        public virtual ICollection<NotesAttachedFile> NotesAttachedFiles { get; set; }
    }
}
