//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotesAttachedFile
    {
        public int Id { get; set; }
        public string FilePath { get; set; }
        public int NoteMessageId { get; set; }
    
        public virtual NotesMessage NotesMessage { get; set; }
    }
}
