//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficialGameReportDetail
    {
        public int Id { get; set; }
        public int UserJobId { get; set; }
        public Nullable<int> GameCycleId { get; set; }
        public Nullable<int> TravelDistance { get; set; }
        public string Comment { get; set; }
    
        public virtual GamesCycle GamesCycle { get; set; }
        public virtual UsersJob UsersJob { get; set; }
    }
}
