//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PenaltyForExclusion
    {
        public PenaltyForExclusion()
        {
            this.GamesCycles = new HashSet<GamesCycle>();
        }
    
        public int Id { get; set; }
        public System.DateTime DateOfExclusion { get; set; }
        public int ExclusionNumber { get; set; }
        public bool IsEnded { get; set; }
        public bool IsCanceled { get; set; }
        public int UserId { get; set; }
        public Nullable<int> ActionUserId { get; set; }
        public string LeagueIds { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<GamesCycle> GamesCycles { get; set; }
    }
}
