//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayersBlockade
    {
        public PlayersBlockade()
        {
            this.Users = new HashSet<User>();
            this.BlockadeNotifications = new HashSet<BlockadeNotification>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool IsActive { get; set; }
        public int BType { get; set; }
        public Nullable<int> SeasonId { get; set; }
        public Nullable<int> ActionUserId { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
        public virtual User User { get; set; }
        public virtual Season Season { get; set; }
        public virtual ICollection<BlockadeNotification> BlockadeNotifications { get; set; }
        public virtual User User1 { get; set; }
    }
}
