//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerAchievement
    {
        public int Id { get; set; }
        public int PlayerId { get; set; }
        public int RankId { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public int Score { get; set; }
    
        public virtual User User { get; set; }
        public virtual SportRank SportRank { get; set; }
    }
}
