//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerDiscount
    {
        public int Id { get; set; }
        public int PlayerId { get; set; }
        public int TeamId { get; set; }
        public Nullable<int> LeagueId { get; set; }
        public int SeasonId { get; set; }
        public int DiscountType { get; set; }
        public decimal Amount { get; set; }
        public int UpdateUserId { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public Nullable<int> ClubId { get; set; }
        public decimal FinalParticipationPrice { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual League League { get; set; }
        public virtual User Player { get; set; }
        public virtual Season Season { get; set; }
        public virtual Team Team { get; set; }
        public virtual User UpdateUser { get; set; }
    }
}
