//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefereeCompetitionRegistration
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int SeasonId { get; set; }
        public int UnionId { get; set; }
        public Nullable<int> LeagueId { get; set; }
        public string SessionIds { get; set; }
    
        public virtual League League { get; set; }
        public virtual Union Union { get; set; }
        public virtual User User { get; set; }
    }
}
