//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Regional
    {
        public Regional()
        {
            this.Clubs = new HashSet<Club>();
        }
    
        public int RegionalId { get; set; }
        public string Name { get; set; }
        public bool IsArchive { get; set; }
        public Nullable<int> UnionId { get; set; }
        public Nullable<int> SeasonId { get; set; }
        public string Logo { get; set; }
        public string PrimaryImage { get; set; }
        public string IndexImage { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Description { get; set; }
        public string IndexAbout { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Season Season { get; set; }
        public virtual Union Union { get; set; }
        public virtual ICollection<Club> Clubs { get; set; }
    }
}
