//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteTeamRank
    {
        public RouteTeamRank()
        {
            this.CompetitionTeamRoutes = new HashSet<CompetitionTeamRoute>();
            this.TeamsRanks = new HashSet<TeamsRank>();
        }
    
        public int Id { get; set; }
        public int TeamRouteId { get; set; }
        public string Rank { get; set; }
        public Nullable<System.DateTime> FromAge { get; set; }
        public Nullable<System.DateTime> ToAge { get; set; }
    
        public virtual ICollection<CompetitionTeamRoute> CompetitionTeamRoutes { get; set; }
        public virtual DisciplineTeamRoute DisciplineTeamRoute { get; set; }
        public virtual ICollection<TeamsRank> TeamsRanks { get; set; }
    }
}
