//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteRank
    {
        public RouteRank()
        {
            this.CompetitionRoutes = new HashSet<CompetitionRoute>();
            this.UsersRanks = new HashSet<UsersRank>();
        }
    
        public int Id { get; set; }
        public int RouteId { get; set; }
        public string Rank { get; set; }
        public Nullable<System.DateTime> FromAge { get; set; }
        public Nullable<System.DateTime> ToAge { get; set; }
        public Nullable<bool> IsArchived { get; set; }
    
        public virtual ICollection<CompetitionRoute> CompetitionRoutes { get; set; }
        public virtual DisciplineRoute DisciplineRoute { get; set; }
        public virtual ICollection<UsersRank> UsersRanks { get; set; }
    }
}
