//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public School()
        {
            this.SchoolTeams = new HashSet<SchoolTeam>();
        }
    
        public int Id { get; set; }
        public int ClubId { get; set; }
        public int SeasonId { get; set; }
        public string Name { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool IsCamp { get; set; }
        public short SortOrder { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual Season Season { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<SchoolTeam> SchoolTeams { get; set; }
    }
}
