//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Season
    {
        public Season()
        {
            this.Games = new HashSet<Game>();
            this.PlayerHistories = new HashSet<PlayerHistory>();
            this.TeamsDetails = new HashSet<TeamsDetails>();
            this.UsersJobs = new HashSet<UsersJob>();
            this.Auditoriums = new HashSet<Auditorium>();
            this.GroupsTeams = new HashSet<GroupsTeam>();
            this.PlayerFiles = new HashSet<PlayerFile>();
            this.Groups = new HashSet<Group>();
            this.TeamsPlayers = new HashSet<TeamsPlayer>();
            this.Leagues = new HashSet<League>();
            this.SentMessages = new HashSet<SentMessage>();
            this.PlayersBenefactorPrices = new HashSet<PlayersBenefactorPrice>();
            this.Schools = new HashSet<School>();
            this.PlayerDiscounts = new HashSet<PlayerDiscount>();
            this.LeagueTeams = new HashSet<LeagueTeams>();
            this.NationalTeamInvitements = new HashSet<NationalTeamInvitement>();
            this.UnionForms = new HashSet<UnionForm>();
            this.PlayersBlockades = new HashSet<PlayersBlockade>();
            this.DistanceTables = new HashSet<DistanceTable>();
            this.PlayerDisciplines = new HashSet<PlayerDiscipline>();
            this.ClubDisciplines = new HashSet<ClubDiscipline>();
            this.TeamDisciplines = new HashSet<TeamDiscipline>();
            this.Activities = new HashSet<Activity>();
            this.ActivityBranches = new HashSet<ActivityBranch>();
            this.CompetitionRoutes = new HashSet<CompetitionRoute>();
            this.CompetitionTeamRoutes = new HashSet<CompetitionTeamRoute>();
            this.CompetitionRegistrations = new HashSet<CompetitionRegistration>();
            this.AdditionalGymnastics = new HashSet<AdditionalGymnastic>();
            this.AdditionalTeamGymnastics = new HashSet<AdditionalTeamGymnastic>();
            this.KarateUnionPayments = new HashSet<KarateUnionPayment>();
            this.TeamRegistrations = new HashSet<TeamRegistration>();
            this.UnionOfficialSettings = new HashSet<UnionOfficialSetting>();
            this.UnionPrices = new HashSet<UnionPrice>();
            this.PositionSettings = new HashSet<PositionSetting>();
            this.RefereeRegistrations = new HashSet<RefereeRegistration>();
            this.Instruments = new HashSet<Instrument>();
            this.Vehicles = new HashSet<Vehicle>();
            this.SportsRegistrations = new HashSet<SportsRegistration>();
            this.CompetitionLevels = new HashSet<CompetitionLevel>();
            this.TennisGames = new HashSet<TennisGame>();
            this.TennisGroups = new HashSet<TennisGroup>();
            this.TennisStages = new HashSet<TennisStage>();
            this.TennisGroupTeams = new HashSet<TennisGroupTeam>();
            this.DaysForHostings = new HashSet<DaysForHosting>();
            this.CompetitionRegions = new HashSet<CompetitionRegion>();
            this.ClubTeams = new HashSet<ClubTeam>();
            this.MedicalCertApprovements = new HashSet<MedicalCertApprovement>();
            this.ClubBalances = new HashSet<ClubBalance>();
            this.CompetitionAges = new HashSet<CompetitionAge>();
            this.CompetitionClubsCorrections = new HashSet<CompetitionClubsCorrection>();
            this.Regionals = new HashSet<Regional>();
            this.AthleticLeagues = new HashSet<AthleticLeague>();
            this.TennisCategoryPlayoffRanks = new HashSet<TennisCategoryPlayoffRank>();
            this.RefereeSalaryReports = new HashSet<RefereeSalaryReport>();
            this.Seasons1 = new HashSet<Season>();
            this.TennisRanks = new HashSet<TennisRank>();
            this.UsersApprovalDatesHistories = new HashSet<UsersApprovalDatesHistory>();
            this.RowingDistances = new HashSet<RowingDistance>();
            this.FriendshipsTypes = new HashSet<FriendshipsType>();
            this.ChipPrices = new HashSet<ChipPrice>();
            this.FriendshipPrices = new HashSet<FriendshipPrice>();
            this.AthleteNumbers = new HashSet<AthleteNumber>();
            this.SeasonRecords = new HashSet<SeasonRecord>();
            this.TeamScheduleScrapperGames = new HashSet<TeamScheduleScrapperGame>();
            this.TeamStandingGames = new HashSet<TeamStandingGame>();
            this.TeamTrainings = new HashSet<TeamTraining>();
            this.LevelPointsSettings = new HashSet<LevelPointsSetting>();
            this.BicycleCompetitionDisciplines = new HashSet<BicycleCompetitionDiscipline>();
            this.BicycleCompetitionHeats = new HashSet<BicycleCompetitionHeat>();
            this.BicycleFriendshipPayments = new HashSet<BicycleFriendshipPayment>();
            this.MedicalInstitutes = new HashSet<MedicalInstitute>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<int> UnionId { get; set; }
        public Nullable<int> ClubId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> MinimumParticipationRequired { get; set; }
        public Nullable<int> PreviousSeasonId { get; set; }
        public Nullable<int> SeasonForAge { get; set; }
    
        public virtual ICollection<Game> Games { get; set; }
        public virtual ICollection<PlayerHistory> PlayerHistories { get; set; }
        public virtual Union Union { get; set; }
        public virtual ICollection<TeamsDetails> TeamsDetails { get; set; }
        public virtual ICollection<UsersJob> UsersJobs { get; set; }
        public virtual Club Club { get; set; }
        public virtual ICollection<Auditorium> Auditoriums { get; set; }
        public virtual ICollection<GroupsTeam> GroupsTeams { get; set; }
        public virtual ICollection<PlayerFile> PlayerFiles { get; set; }
        public virtual ICollection<Group> Groups { get; set; }
        public virtual ICollection<TeamsPlayer> TeamsPlayers { get; set; }
        public virtual ICollection<League> Leagues { get; set; }
        public virtual ICollection<SentMessage> SentMessages { get; set; }
        public virtual ICollection<PlayersBenefactorPrice> PlayersBenefactorPrices { get; set; }
        public virtual ICollection<School> Schools { get; set; }
        public virtual ICollection<PlayerDiscount> PlayerDiscounts { get; set; }
        public virtual ICollection<LeagueTeams> LeagueTeams { get; set; }
        public virtual ICollection<NationalTeamInvitement> NationalTeamInvitements { get; set; }
        public virtual ICollection<UnionForm> UnionForms { get; set; }
        public virtual ICollection<PlayersBlockade> PlayersBlockades { get; set; }
        public virtual ICollection<DistanceTable> DistanceTables { get; set; }
        public virtual ICollection<PlayerDiscipline> PlayerDisciplines { get; set; }
        public virtual ICollection<ClubDiscipline> ClubDisciplines { get; set; }
        public virtual ICollection<TeamDiscipline> TeamDisciplines { get; set; }
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual ICollection<ActivityBranch> ActivityBranches { get; set; }
        public virtual ICollection<CompetitionRoute> CompetitionRoutes { get; set; }
        public virtual ICollection<CompetitionTeamRoute> CompetitionTeamRoutes { get; set; }
        public virtual ICollection<CompetitionRegistration> CompetitionRegistrations { get; set; }
        public virtual ICollection<AdditionalGymnastic> AdditionalGymnastics { get; set; }
        public virtual ICollection<AdditionalTeamGymnastic> AdditionalTeamGymnastics { get; set; }
        public virtual ICollection<KarateUnionPayment> KarateUnionPayments { get; set; }
        public virtual ICollection<TeamRegistration> TeamRegistrations { get; set; }
        public virtual ICollection<UnionOfficialSetting> UnionOfficialSettings { get; set; }
        public virtual ICollection<UnionPrice> UnionPrices { get; set; }
        public virtual ICollection<PositionSetting> PositionSettings { get; set; }
        public virtual ICollection<RefereeRegistration> RefereeRegistrations { get; set; }
        public virtual ICollection<Instrument> Instruments { get; set; }
        public virtual ICollection<Vehicle> Vehicles { get; set; }
        public virtual ICollection<SportsRegistration> SportsRegistrations { get; set; }
        public virtual ICollection<CompetitionLevel> CompetitionLevels { get; set; }
        public virtual ICollection<TennisGame> TennisGames { get; set; }
        public virtual ICollection<TennisGroup> TennisGroups { get; set; }
        public virtual ICollection<TennisStage> TennisStages { get; set; }
        public virtual ICollection<TennisGroupTeam> TennisGroupTeams { get; set; }
        public virtual ICollection<DaysForHosting> DaysForHostings { get; set; }
        public virtual ICollection<CompetitionRegion> CompetitionRegions { get; set; }
        public virtual ICollection<ClubTeam> ClubTeams { get; set; }
        public virtual ICollection<MedicalCertApprovement> MedicalCertApprovements { get; set; }
        public virtual ICollection<ClubBalance> ClubBalances { get; set; }
        public virtual ICollection<CompetitionAge> CompetitionAges { get; set; }
        public virtual ICollection<CompetitionClubsCorrection> CompetitionClubsCorrections { get; set; }
        public virtual ICollection<Regional> Regionals { get; set; }
        public virtual ICollection<AthleticLeague> AthleticLeagues { get; set; }
        public virtual ICollection<TennisCategoryPlayoffRank> TennisCategoryPlayoffRanks { get; set; }
        public virtual ICollection<RefereeSalaryReport> RefereeSalaryReports { get; set; }
        public virtual ICollection<Season> Seasons1 { get; set; }
        public virtual Season Season1 { get; set; }
        public virtual ICollection<TennisRank> TennisRanks { get; set; }
        public virtual ICollection<UsersApprovalDatesHistory> UsersApprovalDatesHistories { get; set; }
        public virtual ICollection<RowingDistance> RowingDistances { get; set; }
        public virtual ICollection<FriendshipsType> FriendshipsTypes { get; set; }
        public virtual ICollection<ChipPrice> ChipPrices { get; set; }
        public virtual ICollection<FriendshipPrice> FriendshipPrices { get; set; }
        public virtual ICollection<AthleteNumber> AthleteNumbers { get; set; }
        public virtual ICollection<SeasonRecord> SeasonRecords { get; set; }
        public virtual ICollection<TeamScheduleScrapperGame> TeamScheduleScrapperGames { get; set; }
        public virtual ICollection<TeamStandingGame> TeamStandingGames { get; set; }
        public virtual ICollection<TeamTraining> TeamTrainings { get; set; }
        public virtual ICollection<LevelPointsSetting> LevelPointsSettings { get; set; }
        public virtual ICollection<BicycleCompetitionDiscipline> BicycleCompetitionDisciplines { get; set; }
        public virtual ICollection<BicycleCompetitionHeat> BicycleCompetitionHeats { get; set; }
        public virtual ICollection<BicycleFriendshipPayment> BicycleFriendshipPayments { get; set; }
        public virtual ICollection<MedicalInstitute> MedicalInstitutes { get; set; }
    }
}
