//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeasonRecord
    {
        public int Id { get; set; }
        public int SeasonId { get; set; }
        public int DisciplineRecordsId { get; set; }
        public string SeasonRecord1 { get; set; }
        public Nullable<long> SeasonRecordSortValue { get; set; }
    
        public virtual DisciplineRecord DisciplineRecord { get; set; }
        public virtual Season Season { get; set; }
    }
}
