//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SportRank
    {
        public SportRank()
        {
            this.PlayerAchievements = new HashSet<PlayerAchievement>();
        }
    
        public int Id { get; set; }
        public int SportId { get; set; }
        public string RankName { get; set; }
        public string RankNameHeb { get; set; }
    
        public virtual ICollection<PlayerAchievement> PlayerAchievements { get; set; }
        public virtual Sport Sport { get; set; }
    }
}
