//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sport
    {
        public Sport()
        {
            this.Unions = new HashSet<Union>();
            this.Clubs = new HashSet<Club>();
            this.SportRanks = new HashSet<SportRank>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int SectionId { get; set; }
        public string NameHeb { get; set; }
    
        public virtual Section Section { get; set; }
        public virtual ICollection<Union> Unions { get; set; }
        public virtual ICollection<Club> Clubs { get; set; }
        public virtual ICollection<SportRank> SportRanks { get; set; }
    }
}
