//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stage
    {
        public Stage()
        {
            this.GamesCycles = new HashSet<GamesCycle>();
            this.Groups = new HashSet<Group>();
            this.ChildStages = new HashSet<Stage>();
            this.TeamPenalties = new HashSet<TeamPenalty>();
        }
    
        public int StageId { get; set; }
        public int Number { get; set; }
        public int LeagueId { get; set; }
        public bool IsArchive { get; set; }
        public string Name { get; set; }
        public bool RankedStandingsEnabled { get; set; }
        public bool CreateCrossesStage { get; set; }
        public bool IsCrossesStage { get; set; }
        public Nullable<int> ParentStageId { get; set; }
    
        public virtual ICollection<GamesCycle> GamesCycles { get; set; }
        public virtual ICollection<Group> Groups { get; set; }
        public virtual League League { get; set; }
        public virtual ICollection<Stage> ChildStages { get; set; }
        public virtual Stage ParentStage { get; set; }
        public virtual ICollection<TeamPenalty> TeamPenalties { get; set; }
    }
}
