//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamsRank
    {
        public int Id { get; set; }
        public int TeamId { get; set; }
        public int RankId { get; set; }
        public int TeamsRouteId { get; set; }
        public int UserId { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual TeamsRoute TeamsRoute { get; set; }
        public virtual User User { get; set; }
        public virtual RouteTeamRank RouteTeamRank { get; set; }
    }
}
