//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamPenalty
    {
        public int Id { get; set; }
        public int StageId { get; set; }
        public int TeamId { get; set; }
        public decimal Points { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual Stage Stage { get; set; }
    }
}
