//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamsRoute
    {
        public TeamsRoute()
        {
            this.TeamsRanks = new HashSet<TeamsRank>();
        }
    
        public int Id { get; set; }
        public int TeamId { get; set; }
        public int RouteId { get; set; }
        public int UserId { get; set; }
    
        public virtual DisciplineRoute DisciplineRoute { get; set; }
        public virtual Team Team { get; set; }
        public virtual ICollection<TeamsRank> TeamsRanks { get; set; }
        public virtual DisciplineTeamRoute DisciplineTeamRoute { get; set; }
        public virtual User User { get; set; }
    }
}
