//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamRegistration
    {
        public TeamRegistration()
        {
            this.TeamRegistrationPayments = new HashSet<TeamRegistrationPayment>();
            this.TeamsDetails = new HashSet<TeamsDetails>();
        }
    
        public int Id { get; set; }
        public int TeamId { get; set; }
        public int ClubId { get; set; }
        public int LeagueId { get; set; }
        public Nullable<int> SeasonId { get; set; }
        public string TeamName { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual League League { get; set; }
        public virtual Season Season { get; set; }
        public virtual Team Team { get; set; }
        public virtual ICollection<TeamRegistrationPayment> TeamRegistrationPayments { get; set; }
        public virtual ICollection<TeamsDetails> TeamsDetails { get; set; }
    }
}
