//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamRegistrationPayment
    {
        public int Id { get; set; }
        public int TeamRegistrationId { get; set; }
        public int ClubBalanceId { get; set; }
        public Nullable<decimal> Fee { get; set; }
    
        public virtual ClubBalance ClubBalances { get; set; }
        public virtual TeamRegistration TeamRegistrations { get; set; }
    }
}
