//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public Team()
        {
            this.GuestTeamGamesCycles = new HashSet<GamesCycle>();
            this.HomeTeamGamesCycles = new HashSet<GamesCycle>();
            this.GroupsTeams = new HashSet<GroupsTeam>();
            this.LeagueTeams = new HashSet<LeagueTeams>();
            this.PlayerHistories = new HashSet<PlayerHistory>();
            this.PlayoffBrackets = new HashSet<PlayoffBracket>();
            this.PlayoffBrackets1 = new HashSet<PlayoffBracket>();
            this.PlayoffBrackets2 = new HashSet<PlayoffBracket>();
            this.PlayoffBrackets3 = new HashSet<PlayoffBracket>();
            this.RetirementRequests = new HashSet<RetirementRequest>();
            this.TeamsAuditoriums = new HashSet<TeamsAuditorium>();
            this.TeamsFans = new HashSet<TeamsFan>();
            this.TeamsDetails = new HashSet<TeamsDetails>();
            this.TeamStandingGames = new HashSet<TeamStandingGame>();
            this.UsersJobs = new HashSet<UsersJob>();
            this.WallThreads = new HashSet<WallThread>();
            this.NotesMessages = new HashSet<NotesMessage>();
            this.TeamsPlayers = new HashSet<TeamsPlayer>();
            this.SentMessages = new HashSet<SentMessage>();
            this.TeamBenefactors = new HashSet<TeamBenefactor>();
            this.TeamTrainings = new HashSet<TeamTraining>();
            this.PlayersBenefactorPrices = new HashSet<PlayersBenefactorPrice>();
            this.SchoolTeams = new HashSet<SchoolTeam>();
            this.ClubTeamPrices = new HashSet<ClubTeamPrice>();
            this.PlayerDiscounts = new HashSet<PlayerDiscount>();
            this.PlayerHistories1 = new HashSet<PlayerHistory>();
            this.Statistics = new HashSet<Statistic>();
            this.GameStatistics = new HashSet<GameStatistic>();
            this.TeamDisciplines = new HashSet<TeamDiscipline>();
            this.ActivityFormsSubmittedDatas = new HashSet<ActivityFormsSubmittedData>();
            this.TeamRegistrations = new HashSet<TeamRegistration>();
            this.TeamPenalties = new HashSet<TeamPenalty>();
            this.TennisGames = new HashSet<TennisGame>();
            this.TennisStages = new HashSet<TennisStage>();
            this.TeamHostingDays = new HashSet<TeamHostingDay>();
            this.ClubTeams = new HashSet<ClubTeam>();
            this.CategoriesPlaceDates = new HashSet<CategoriesPlaceDate>();
            this.TeamsRanks = new HashSet<TeamsRank>();
            this.TeamsRoutes = new HashSet<TeamsRoute>();
            this.RankedStandingCorrections = new HashSet<RankedStandingCorrection>();
            this.TennisCategoryPlayoffRanks = new HashSet<TennisCategoryPlayoffRank>();
            this.BicycleFriendshipPayments = new HashSet<BicycleFriendshipPayment>();
            this.WaterpoloStatistics = new HashSet<WaterpoloStatistic>();
        }
    
        public int TeamId { get; set; }
        public string Title { get; set; }
        public string Logo { get; set; }
        public string PersonnelPic { get; set; }
        public string Description { get; set; }
        public string OrgUrl { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsArchive { get; set; }
        public string GamesUrl { get; set; }
        public Nullable<bool> IsUnderAdult { get; set; }
        public Nullable<bool> IsReserved { get; set; }
        public Nullable<bool> NeedShirts { get; set; }
        public string InsuranceApproval { get; set; }
        public Nullable<bool> HasArena { get; set; }
        public bool IsTrainingEnabled { get; set; }
        public Nullable<System.DateTime> MinimumAge { get; set; }
        public Nullable<System.DateTime> MaximumAge { get; set; }
        public Nullable<int> CompetitionAgeId { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> LevelId { get; set; }
        public Nullable<int> MinRank { get; set; }
        public Nullable<int> MaxRank { get; set; }
        public string PlaceForQualification { get; set; }
        public string PlaceForFinal { get; set; }
        public bool IsReligiousTeam { get; set; }
        public Nullable<bool> IsUnionInsurance { get; set; }
        public Nullable<bool> IsClubInsurance { get; set; }
        public bool IsRankCalculated { get; set; }
        public short SortOrder { get; set; }
        public Nullable<int> MonthlyProvisionForSecurity { get; set; }
    
        public virtual ICollection<GamesCycle> GuestTeamGamesCycles { get; set; }
        public virtual ICollection<GamesCycle> HomeTeamGamesCycles { get; set; }
        public virtual ICollection<GroupsTeam> GroupsTeams { get; set; }
        public virtual ICollection<LeagueTeams> LeagueTeams { get; set; }
        public virtual ICollection<PlayerHistory> PlayerHistories { get; set; }
        public virtual ICollection<PlayoffBracket> PlayoffBrackets { get; set; }
        public virtual ICollection<PlayoffBracket> PlayoffBrackets1 { get; set; }
        public virtual ICollection<PlayoffBracket> PlayoffBrackets2 { get; set; }
        public virtual ICollection<PlayoffBracket> PlayoffBrackets3 { get; set; }
        public virtual ICollection<RetirementRequest> RetirementRequests { get; set; }
        public virtual ICollection<TeamsAuditorium> TeamsAuditoriums { get; set; }
        public virtual ICollection<TeamsFan> TeamsFans { get; set; }
        public virtual ICollection<TeamsDetails> TeamsDetails { get; set; }
        public virtual ICollection<TeamStandingGame> TeamStandingGames { get; set; }
        public virtual ICollection<UsersJob> UsersJobs { get; set; }
        public virtual ICollection<WallThread> WallThreads { get; set; }
        public virtual ICollection<NotesMessage> NotesMessages { get; set; }
        public virtual ICollection<TeamsPlayer> TeamsPlayers { get; set; }
        public virtual ICollection<SentMessage> SentMessages { get; set; }
        public virtual ICollection<TeamBenefactor> TeamBenefactors { get; set; }
        public virtual ICollection<TeamTraining> TeamTrainings { get; set; }
        public virtual ICollection<PlayersBenefactorPrice> PlayersBenefactorPrices { get; set; }
        public virtual ICollection<SchoolTeam> SchoolTeams { get; set; }
        public virtual ICollection<ClubTeamPrice> ClubTeamPrices { get; set; }
        public virtual ICollection<PlayerDiscount> PlayerDiscounts { get; set; }
        public virtual ICollection<PlayerHistory> PlayerHistories1 { get; set; }
        public virtual ICollection<Statistic> Statistics { get; set; }
        public virtual ICollection<GameStatistic> GameStatistics { get; set; }
        public virtual ICollection<TeamDiscipline> TeamDisciplines { get; set; }
        public virtual ICollection<ActivityFormsSubmittedData> ActivityFormsSubmittedDatas { get; set; }
        public virtual ICollection<TeamRegistration> TeamRegistrations { get; set; }
        public virtual ICollection<TeamPenalty> TeamPenalties { get; set; }
        public virtual CompetitionLevel CompetitionLevel { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual ICollection<TennisGame> TennisGames { get; set; }
        public virtual ICollection<TennisStage> TennisStages { get; set; }
        public virtual ICollection<TeamHostingDay> TeamHostingDays { get; set; }
        public virtual CompetitionRegion CompetitionRegion { get; set; }
        public virtual ICollection<ClubTeam> ClubTeams { get; set; }
        public virtual ICollection<CategoriesPlaceDate> CategoriesPlaceDates { get; set; }
        public virtual ICollection<TeamsRank> TeamsRanks { get; set; }
        public virtual ICollection<TeamsRoute> TeamsRoutes { get; set; }
        public virtual CompetitionAge CompetitionAge { get; set; }
        public virtual ICollection<RankedStandingCorrection> RankedStandingCorrections { get; set; }
        public virtual ICollection<TennisCategoryPlayoffRank> TennisCategoryPlayoffRanks { get; set; }
        public virtual ICollection<BicycleFriendshipPayment> BicycleFriendshipPayments { get; set; }
        public virtual ICollection<WaterpoloStatistic> WaterpoloStatistics { get; set; }
    }
}
