//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamTraining
    {
        public TeamTraining()
        {
            this.TrainingAttendances = new HashSet<TrainingAttendance>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public int TeamId { get; set; }
        public Nullable<int> AuditoriumId { get; set; }
        public System.DateTime TrainingDate { get; set; }
        public string Content { get; set; }
        public bool isPublished { get; set; }
        public string TrainingReport { get; set; }
        public Nullable<int> SeasonId { get; set; }
    
        public virtual Auditorium Auditorium { get; set; }
        public virtual Team Team { get; set; }
        public virtual ICollection<TrainingAttendance> TrainingAttendances { get; set; }
        public virtual Season Season { get; set; }
    }
}
