//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TennisGame
    {
        public int GameId { get; set; }
        public int CategoryId { get; set; }
        public string GameDays { get; set; }
        public System.DateTime StartDate { get; set; }
        public string GamesInterval { get; set; }
        public int PointsWin { get; set; }
        public int PointsDraw { get; set; }
        public int PointsLoss { get; set; }
        public int PointTechWin { get; set; }
        public string SortDescriptions { get; set; }
        public int PointsTechLoss { get; set; }
        public Nullable<int> StageId { get; set; }
        public Nullable<int> SeasonId { get; set; }
        public int ActiveWeeksNumber { get; set; }
        public int BreakWeeksNumber { get; set; }
        public Nullable<int> RoundStartCycle { get; set; }
        public Nullable<int> ShowCyclesOnExternal { get; set; }
        public Nullable<bool> IsDateForFirstCycleOnly { get; set; }
    
        public virtual Season Season { get; set; }
        public virtual Team Team { get; set; }
        public virtual TennisStage TennisStage { get; set; }
    }
}
