//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TennisRank
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<int> Points { get; set; }
        public Nullable<int> AgeId { get; set; }
        public bool IsUpdated { get; set; }
        public Nullable<int> AveragePoints { get; set; }
        public Nullable<int> PointsToAverage { get; set; }
        public Nullable<int> SeasonId { get; set; }
    
        public virtual User User { get; set; }
        public virtual CompetitionAge CompetitionAge { get; set; }
        public virtual Season Season { get; set; }
    }
}
