//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TennisPlayoffBracket
    {
        public TennisPlayoffBracket()
        {
            this.TennisGameCycles = new HashSet<TennisGameCycle>();
            this.TennisPlayoffBrackets1 = new HashSet<TennisPlayoffBracket>();
            this.TennisPlayoffBrackets11 = new HashSet<TennisPlayoffBracket>();
        }
    
        public int Id { get; set; }
        public int MaxPos { get; set; }
        public int MinPos { get; set; }
        public Nullable<int> WinnerId { get; set; }
        public Nullable<int> LoserId { get; set; }
        public int GroupId { get; set; }
        public Nullable<int> ParentBracket1Id { get; set; }
        public Nullable<int> ParentBracket2Id { get; set; }
        public int Type { get; set; }
        public int Stage { get; set; }
        public Nullable<int> FirstPlayerId { get; set; }
        public Nullable<int> SecondPlayerId { get; set; }
        public Nullable<int> FirstPlayerPairId { get; set; }
        public Nullable<int> SecondPlayerPairId { get; set; }
        public Nullable<int> WinnerPlayerPairId { get; set; }
        public Nullable<int> LoserPlayerPairId { get; set; }
    
        public virtual ICollection<TennisGameCycle> TennisGameCycles { get; set; }
        public virtual TennisGroup TennisGroup { get; set; }
        public virtual ICollection<TennisPlayoffBracket> TennisPlayoffBrackets1 { get; set; }
        public virtual TennisPlayoffBracket TennisPlayoffBracket1 { get; set; }
        public virtual ICollection<TennisPlayoffBracket> TennisPlayoffBrackets11 { get; set; }
        public virtual TennisPlayoffBracket TennisPlayoffBracket2 { get; set; }
    }
}
