//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TennisStage
    {
        public TennisStage()
        {
            this.TennisGameCycles = new HashSet<TennisGameCycle>();
            this.TennisGames = new HashSet<TennisGame>();
            this.TennisGroups = new HashSet<TennisGroup>();
        }
    
        public int StageId { get; set; }
        public int Number { get; set; }
        public int CategoryId { get; set; }
        public bool IsArchive { get; set; }
        public int SeasonId { get; set; }
    
        public virtual Season Season { get; set; }
        public virtual Team Team { get; set; }
        public virtual ICollection<TennisGameCycle> TennisGameCycles { get; set; }
        public virtual ICollection<TennisGame> TennisGames { get; set; }
        public virtual ICollection<TennisGroup> TennisGroups { get; set; }
    }
}
