//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TennisCategoryPlayoffRank
    {
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public int LeagueId { get; set; }
        public int SeasonId { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> Points { get; set; }
        public Nullable<int> PlayerId { get; set; }
        public Nullable<int> PairPlayerId { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<int> RealMaxPos { get; set; }
        public Nullable<int> RealMinPos { get; set; }
        public Nullable<int> Correction { get; set; }
    
        public virtual League League { get; set; }
        public virtual Season Season { get; set; }
        public virtual Team Team { get; set; }
        public virtual TeamsPlayer TeamsPlayer { get; set; }
        public virtual TeamsPlayer TeamsPlayer1 { get; set; }
    }
}
