//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TennisGameCycle
    {
        public TennisGameCycle()
        {
            this.TennisGameSets = new HashSet<TennisGameSet>();
        }
    
        public int CycleId { get; set; }
        public int StageId { get; set; }
        public int CycleNum { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<int> FieldId { get; set; }
        public Nullable<int> FirstPlayerId { get; set; }
        public int FirstPlayerScore { get; set; }
        public Nullable<int> SecondPlayerId { get; set; }
        public int SecondPlayerScore { get; set; }
        public string RefereeIds { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string GameStatus { get; set; }
        public Nullable<int> TechnicalWinnerId { get; set; }
        public Nullable<int> MaxPlayoffPos { get; set; }
        public Nullable<int> MinPlayoffPos { get; set; }
        public Nullable<int> BracketId { get; set; }
        public bool IsPublished { get; set; }
        public Nullable<int> BracketIndex { get; set; }
        public string SpectatorIds { get; set; }
        public string PdfGameReport { get; set; }
        public string Note { get; set; }
        public bool IsDateUpdated { get; set; }
        public Nullable<int> FirstPlayerPos { get; set; }
        public Nullable<int> SecondPlayerPos { get; set; }
        public Nullable<int> FirstPlayerPairId { get; set; }
        public Nullable<int> SecondPlayerPairId { get; set; }
        public Nullable<int> RoundNum { get; set; }
        public bool IsNotSetYet { get; set; }
        public string TimeInitial { get; set; }
    
        public virtual Auditorium Auditorium { get; set; }
        public virtual TeamsPlayer TeamsPlayer { get; set; }
        public virtual TeamsPlayer TeamsPlayer1 { get; set; }
        public virtual TennisGroup TennisGroup { get; set; }
        public virtual TennisStage TennisStage { get; set; }
        public virtual ICollection<TennisGameSet> TennisGameSets { get; set; }
        public virtual TennisPlayoffBracket TennisPlayoffBracket { get; set; }
        public virtual TeamsPlayer TeamsPlayer11 { get; set; }
        public virtual TeamsPlayer TeamsPlayer3 { get; set; }
    }
}
