//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingSetting
    {
        public int Id { get; set; }
        public string DurationTraining { get; set; }
        public bool ConsiderationHolidays { get; set; }
        public bool TrainingSameDay { get; set; }
        public bool TrainingBeforeGame { get; set; }
        public string MinNumTrainingDays { get; set; }
        public bool NoTwoTraining { get; set; }
        public bool TrainingFollowDay { get; set; }
        public Nullable<int> TeamID { get; set; }
        public bool NoDayAfterDayTrainings { get; set; }
    }
}
