//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingAttendance
    {
        public int Id { get; set; }
        public int TrainingId { get; set; }
        public int PlayerId { get; set; }
    
        public virtual TeamsPlayer TeamsPlayer { get; set; }
        public virtual TeamTraining TeamTraining { get; set; }
    }
}
