//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingDaysSetting
    {
        public int TrainingSettingsId { get; set; }
        public int TeamId { get; set; }
        public int AuditoriumId { get; set; }
        public string TrainingDay { get; set; }
        public string TrainingStartTime { get; set; }
        public string TrainingEndTime { get; set; }
    }
}
