//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnionPrice
    {
        public int Id { get; set; }
        public int UnionId { get; set; }
        public decimal Price { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int PriceType { get; set; }
        public int SeasonId { get; set; }
        public Nullable<System.DateTime> FromBirthday { get; set; }
        public Nullable<System.DateTime> ToBirthday { get; set; }
        public string CardComProductId { get; set; }
    
        public virtual Union Union { get; set; }
        public virtual Season Season { get; set; }
    }
}
