//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Union
    {
        public Union()
        {
            this.UnionsDocs = new HashSet<UnionsDoc>();
            this.UsersJobs = new HashSet<UsersJob>();
            this.Seasons = new HashSet<Season>();
            this.Clubs = new HashSet<Club>();
            this.Auditoriums = new HashSet<Auditorium>();
            this.Leagues = new HashSet<League>();
            this.SentMessages = new HashSet<SentMessage>();
            this.Disciplines = new HashSet<Discipline>();
            this.UnionForms = new HashSet<UnionForm>();
            this.DistanceTables = new HashSet<DistanceTable>();
            this.Activities = new HashSet<Activity>();
            this.ActivityBranches = new HashSet<ActivityBranch>();
            this.KarateUnionPayments = new HashSet<KarateUnionPayment>();
            this.UnionOfficialSettings = new HashSet<UnionOfficialSetting>();
            this.UnionPrices = new HashSet<UnionPrice>();
            this.Vehicles = new HashSet<Vehicle>();
            this.AdvBanners = new HashSet<AdvBanner>();
            this.InitialApprovalDates = new HashSet<InitialApprovalDate>();
            this.CompetitionLevels = new HashSet<CompetitionLevel>();
            this.CompetitionRegions = new HashSet<CompetitionRegion>();
            this.CompetitionAges = new HashSet<CompetitionAge>();
            this.RefereeCompetitionRegistrations = new HashSet<RefereeCompetitionRegistration>();
            this.Regionals = new HashSet<Regional>();
            this.FriendshipsTypes = new HashSet<FriendshipsType>();
            this.ChipPrices = new HashSet<ChipPrice>();
            this.FriendshipPrices = new HashSet<FriendshipPrice>();
            this.DisciplineRecords = new HashSet<DisciplineRecord>();
            this.Events = new HashSet<Event>();
            this.BicycleCompetitionDisciplines = new HashSet<BicycleCompetitionDiscipline>();
            this.BicycleCompetitionHeats = new HashSet<BicycleCompetitionHeat>();
            this.MedicalInstitutes = new HashSet<MedicalInstitute>();
        }
    
        public int UnionId { get; set; }
        public int SectionId { get; set; }
        public string Name { get; set; }
        public bool IsArchive { get; set; }
        public string Logo { get; set; }
        public string PrimaryImage { get; set; }
        public string Description { get; set; }
        public string IndexImage { get; set; }
        public string IndexAbout { get; set; }
        public string TermsCondition { get; set; }
        public string ContactPhone { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public bool IsHadicapEnabled { get; set; }
        public Nullable<int> SportType { get; set; }
        public bool IsReportsEnabled { get; set; }
        public string StatementOfClub { get; set; }
        public string DistanceSettings { get; set; }
        public Nullable<long> UnionNumber { get; set; }
        public bool IsOfficialSettingsChecked { get; set; }
        public bool EnablePaymentsForPlayerClubRegistrations { get; set; }
        public string ReportSettings { get; set; }
        public bool IsClubsBlocked { get; set; }
        public Nullable<bool> SaturdaysTariff { get; set; }
        public Nullable<System.DateTime> SaturdaysTariffFromTime { get; set; }
        public Nullable<System.DateTime> SaturdaysTariffToTime { get; set; }
        public bool ReportRemoveTravelDistance { get; set; }
        public bool IsRegionallevelEnabled { get; set; }
        public Nullable<int> TotoReportMaxBirthYear { get; set; }
        public Nullable<bool> ApprovePlayerByClubManagerFirst { get; set; }
        public string ContentForFriendshipCard { get; set; }
        public bool EnableIDCorrectionCheck { get; set; }
        public string UnionForeignName { get; set; }
        public string ForeignAddress { get; set; }
        public string UnionWebSite { get; set; }
    
        public virtual Section Section { get; set; }
        public virtual ICollection<UnionsDoc> UnionsDocs { get; set; }
        public virtual ICollection<UsersJob> UsersJobs { get; set; }
        public virtual ICollection<Season> Seasons { get; set; }
        public virtual ICollection<Club> Clubs { get; set; }
        public virtual ICollection<Auditorium> Auditoriums { get; set; }
        public virtual Sport Sport { get; set; }
        public virtual ICollection<League> Leagues { get; set; }
        public virtual ICollection<SentMessage> SentMessages { get; set; }
        public virtual ICollection<Discipline> Disciplines { get; set; }
        public virtual ICollection<UnionForm> UnionForms { get; set; }
        public virtual ICollection<DistanceTable> DistanceTables { get; set; }
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual ICollection<ActivityBranch> ActivityBranches { get; set; }
        public virtual ICollection<KarateUnionPayment> KarateUnionPayments { get; set; }
        public virtual ICollection<UnionOfficialSetting> UnionOfficialSettings { get; set; }
        public virtual ICollection<UnionPrice> UnionPrices { get; set; }
        public virtual ICollection<Vehicle> Vehicles { get; set; }
        public virtual ICollection<AdvBanner> AdvBanners { get; set; }
        public virtual ICollection<InitialApprovalDate> InitialApprovalDates { get; set; }
        public virtual ICollection<CompetitionLevel> CompetitionLevels { get; set; }
        public virtual ICollection<CompetitionRegion> CompetitionRegions { get; set; }
        public virtual ICollection<CompetitionAge> CompetitionAges { get; set; }
        public virtual ICollection<RefereeCompetitionRegistration> RefereeCompetitionRegistrations { get; set; }
        public virtual ICollection<Regional> Regionals { get; set; }
        public virtual ICollection<FriendshipsType> FriendshipsTypes { get; set; }
        public virtual ICollection<ChipPrice> ChipPrices { get; set; }
        public virtual ICollection<FriendshipPrice> FriendshipPrices { get; set; }
        public virtual ICollection<DisciplineRecord> DisciplineRecords { get; set; }
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<BicycleCompetitionDiscipline> BicycleCompetitionDisciplines { get; set; }
        public virtual ICollection<BicycleCompetitionHeat> BicycleCompetitionHeats { get; set; }
        public virtual ICollection<MedicalInstitute> MedicalInstitutes { get; set; }
    }
}
