//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersJob
    {
        public UsersJob()
        {
            this.KarateRefereesRanks = new HashSet<KarateRefereesRank>();
            this.RefereeRegistrations = new HashSet<RefereeRegistration>();
            this.OfficialGameReportDetails = new HashSet<OfficialGameReportDetail>();
            this.TravelInformations = new HashSet<TravelInformation>();
        }
    
        public int Id { get; set; }
        public int JobId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> UnionId { get; set; }
        public Nullable<int> LeagueId { get; set; }
        public Nullable<int> TeamId { get; set; }
        public Nullable<int> ClubId { get; set; }
        public Nullable<int> SeasonId { get; set; }
        public Nullable<int> DisciplineId { get; set; }
        public Nullable<int> WithhodlingTax { get; set; }
        public string RateType { get; set; }
        public Nullable<int> ConnectedClubId { get; set; }
        public bool IsBlocked { get; set; }
        public string ConnectedDisciplineIds { get; set; }
        public bool IsCompetitionRegistrationBlocked { get; set; }
        public Nullable<int> RegionalId { get; set; }
        public bool Active { get; set; }
        public string FormatPermissions { get; set; }
        public string Function { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual Union Union { get; set; }
        public virtual Season Season { get; set; }
        public virtual User User { get; set; }
        public virtual Team Team { get; set; }
        public virtual League League { get; set; }
        public virtual Discipline Discipline { get; set; }
        public virtual Club Club { get; set; }
        public virtual ICollection<KarateRefereesRank> KarateRefereesRanks { get; set; }
        public virtual Club Club1 { get; set; }
        public virtual ICollection<RefereeRegistration> RefereeRegistrations { get; set; }
        public virtual ICollection<OfficialGameReportDetail> OfficialGameReportDetails { get; set; }
        public virtual ICollection<TravelInformation> TravelInformations { get; set; }
    }
}
