//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersRank
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int RankId { get; set; }
        public int UsersRouteId { get; set; }
    
        public virtual User User { get; set; }
        public virtual UsersRoute UsersRoute { get; set; }
        public virtual RouteRank RouteRank { get; set; }
    }
}
