//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Messages = new HashSet<Message>();
            this.NotesRecipients = new HashSet<NotesRecipient>();
            this.PlayerHistories = new HashSet<PlayerHistory>();
            this.TeamsFans = new HashSet<TeamsFan>();
            this.UsersDvices = new HashSet<UsersDvice>();
            this.Friends = new HashSet<UsersFriend>();
            this.UsersFriends = new HashSet<UsersFriend>();
            this.UsersJobs = new HashSet<UsersJob>();
            this.WallThreads = new HashSet<WallThread>();
            this.Notifications = new HashSet<Notification>();
            this.PlayerAchievements = new HashSet<PlayerAchievement>();
            this.PlayerFiles = new HashSet<PlayerFile>();
            this.ApprovedRetirementRequests = new HashSet<RetirementRequest>();
            this.RetirementRequests = new HashSet<RetirementRequest>();
            this.UsersGamesCycles = new HashSet<GamesCycle>();
            this.TeamsPlayers = new HashSet<TeamsPlayer>();
            this.SentMessages = new HashSet<SentMessage>();
            this.PlayersBenefactorPrices = new HashSet<PlayersBenefactorPrice>();
            this.Schools = new HashSet<School>();
            this.PlayerDiscounts = new HashSet<PlayerDiscount>();
            this.PlayerDiscounts1 = new HashSet<PlayerDiscount>();
            this.PlayersBlockades = new HashSet<PlayersBlockade>();
            this.BlockadeNotifications = new HashSet<BlockadeNotification>();
            this.UsersRanks = new HashSet<UsersRank>();
            this.UsersRoutes = new HashSet<UsersRoute>();
            this.PlayerDisciplines = new HashSet<PlayerDiscipline>();
            this.ActivitiesUsers = new HashSet<ActivitiesUser>();
            this.ActivityForms = new HashSet<ActivityForm>();
            this.ActivityForms1 = new HashSet<ActivityForm>();
            this.ActivityFormsSubmittedDatas = new HashSet<ActivityFormsSubmittedData>();
            this.ActivityStatusColumnsVisibilities = new HashSet<ActivityStatusColumnsVisibility>();
            this.CompetitionRegistrations = new HashSet<CompetitionRegistration>();
            this.AdditionalGymnastics = new HashSet<AdditionalGymnastic>();
            this.AdditionalTeamGymnastics = new HashSet<AdditionalTeamGymnastic>();
            this.TeamScheduleScrappers1 = new HashSet<TeamScheduleScrapper>();
            this.UsersEducations = new HashSet<UsersEducation>();
            this.DisplayedPaymentMessages = new HashSet<DisplayedPaymentMessage>();
            this.NotesMessages = new HashSet<NotesMessage>();
            this.SportsRegistrations = new HashSet<SportsRegistration>();
            this.PenaltyForExclusions = new HashSet<PenaltyForExclusion>();
            this.InitialApprovalDates = new HashSet<InitialApprovalDate>();
            this.UsersApprovalDatesHistories = new HashSet<UsersApprovalDatesHistory>();
            this.ActivityStatusColumnNames = new HashSet<ActivityStatusColumnName>();
            this.ActivityStatusColumnsOrders = new HashSet<ActivityStatusColumnsOrder>();
            this.ActivityStatusColumnsSortings = new HashSet<ActivityStatusColumnsSorting>();
            this.TennisLeagueGames = new HashSet<TennisLeagueGame>();
            this.TennisLeagueGames1 = new HashSet<TennisLeagueGame>();
            this.TennisLeagueGames2 = new HashSet<TennisLeagueGame>();
            this.TennisLeagueGames3 = new HashSet<TennisLeagueGame>();
            this.TennisLeagueGames21 = new HashSet<TennisLeagueGame>();
            this.ActivityBranchesStates = new HashSet<ActivityBranchesState>();
            this.TennisRanks = new HashSet<TennisRank>();
            this.LeagueScheduleStates = new HashSet<LeagueScheduleState>();
            this.MedicalCertApprovements = new HashSet<MedicalCertApprovement>();
            this.PenaltyForExclusions1 = new HashSet<PenaltyForExclusion>();
            this.PlayerHistories1 = new HashSet<PlayerHistory>();
            this.PlayersBlockades1 = new HashSet<PlayersBlockade>();
            this.TeamsPlayers1 = new HashSet<TeamsPlayer>();
            this.UsersApprovalDatesHistories1 = new HashSet<UsersApprovalDatesHistory>();
            this.LeaguesFans = new HashSet<LeaguesFan>();
            this.ClubBalances = new HashSet<ClubBalance>();
            this.CompetitionDisciplineRegistrations = new HashSet<CompetitionDisciplineRegistration>();
            this.TeamsRanks = new HashSet<TeamsRank>();
            this.TeamsRoutes = new HashSet<TeamsRoute>();
            this.RefereeCompetitionRegistrations = new HashSet<RefereeCompetitionRegistration>();
            this.RefereeSalaryReports = new HashSet<RefereeSalaryReport>();
            this.ResetPasswordRequests = new HashSet<ResetPasswordRequest>();
            this.TeamsPlayers2 = new HashSet<TeamsPlayer>();
            this.ActivityFormsSubmittedDatas1 = new HashSet<ActivityFormsSubmittedData>();
            this.AthleteNumbers = new HashSet<AthleteNumber>();
            this.BicycleFriendshipPayments = new HashSet<BicycleFriendshipPayment>();
            this.BicycleDisciplineRegistrations = new HashSet<BicycleDisciplineRegistration>();
            this.DiscardedBicycleFriendshipPayments = new HashSet<BicycleFriendshipPayment>();
            this.CreatedBicycleFriendshipPayments = new HashSet<BicycleFriendshipPayment>();
        }
    
        public int UserId { get; set; }
        public int TypeId { get; set; }
        public string FbId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string IdentNum { get; set; }
        public string IdentCard { get; set; }
        public bool IsActive { get; set; }
        public string Password { get; set; }
        public string PassHint { get; set; }
        public int TriesNum { get; set; }
        public bool IsBlocked { get; set; }
        public string SessionId { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string City { get; set; }
        public string Image { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> GenderId { get; set; }
        public bool IsArchive { get; set; }
        public string Telephone { get; set; }
        public Nullable<bool> MedicalCertificate { get; set; }
        public Nullable<bool> Insurance { get; set; }
        public Nullable<int> LangId { get; set; }
        public int TestResults { get; set; }
        public string InsuranceFile { get; set; }
        public string MedicalCertificateFile { get; set; }
        public string ShirtSize { get; set; }
        public string WeightUnits { get; set; }
        public Nullable<System.DateTime> WeightDate { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<bool> IsStartAlert { get; set; }
        public Nullable<bool> IsTimeChange { get; set; }
        public Nullable<bool> IsGameScores { get; set; }
        public string ParentName { get; set; }
        public bool NoInsurancePayment { get; set; }
        public string PassportNum { get; set; }
        public string Address { get; set; }
        public string IDFile { get; set; }
        public Nullable<int> BlockadeId { get; set; }
        public Nullable<System.DateTime> DateOfInsurance { get; set; }
        public Nullable<System.DateTime> TenicardValidity { get; set; }
        public Nullable<System.DateTime> MedExamDate { get; set; }
        public string CompetitiveLicenseNumber { get; set; }
        public Nullable<System.DateTime> LicenseValidity { get; set; }
        public string LicenseLevel { get; set; }
        public bool IsCompetitiveMember { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PassportFile { get; set; }
        public Nullable<System.DateTime> ArgometricTestValidity { get; set; }
        public string RefereeCertificate { get; set; }
        public Nullable<int> SeasonIdOfCreation { get; set; }
        public Nullable<int> ClassS { get; set; }
        public Nullable<int> ClassSB { get; set; }
        public Nullable<int> ClassSM { get; set; }
        public string DeprecatedFullName { get; set; }
        public Nullable<long> UciId { get; set; }
        public string ChipNumber { get; set; }
        public Nullable<bool> IsNationalSportsman { get; set; }
        public Nullable<int> ShoesSize { get; set; }
        public Nullable<System.DateTime> ArmyDraftDate { get; set; }
        public string MedicalInformation { get; set; }
        public Nullable<int> AuditoriumId { get; set; }
        public string MiddleName { get; set; }
        public string ForeignFirstName { get; set; }
        public string MotherName { get; set; }
        public string ParentPhone { get; set; }
        public string ParentEmail { get; set; }
        public string ForeignLastName { get; set; }
        public string LastCmsCulture { get; set; }
        public string PostalCode { get; set; }
        public Nullable<bool> PaymentForUciId { get; set; }
        public Nullable<bool> PaymentForChipNumber { get; set; }
        public string Nationality { get; set; }
        public Nullable<System.DateTime> PassportValidity { get; set; }
        public string CountryOfBirth { get; set; }
        public Nullable<int> InsuranceTypeId { get; set; }
        public Nullable<bool> IsReligious { get; set; }
        public Nullable<int> HeatTypeForUciCard { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<NotesRecipient> NotesRecipients { get; set; }
        public virtual ICollection<PlayerHistory> PlayerHistories { get; set; }
        public virtual ICollection<TeamsFan> TeamsFans { get; set; }
        public virtual UsersType UsersType { get; set; }
        public virtual ICollection<UsersDvice> UsersDvices { get; set; }
        public virtual ICollection<UsersFriend> Friends { get; set; }
        public virtual ICollection<UsersFriend> UsersFriends { get; set; }
        public virtual ICollection<UsersJob> UsersJobs { get; set; }
        public virtual ICollection<WallThread> WallThreads { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual ICollection<PlayerAchievement> PlayerAchievements { get; set; }
        public virtual ICollection<PlayerFile> PlayerFiles { get; set; }
        public virtual ICollection<RetirementRequest> ApprovedRetirementRequests { get; set; }
        public virtual ICollection<RetirementRequest> RetirementRequests { get; set; }
        public virtual ICollection<GamesCycle> UsersGamesCycles { get; set; }
        public virtual ICollection<TeamsPlayer> TeamsPlayers { get; set; }
        public virtual ICollection<SentMessage> SentMessages { get; set; }
        public virtual ICollection<PlayersBenefactorPrice> PlayersBenefactorPrices { get; set; }
        public virtual ICollection<School> Schools { get; set; }
        public virtual ICollection<PlayerDiscount> PlayerDiscounts { get; set; }
        public virtual ICollection<PlayerDiscount> PlayerDiscounts1 { get; set; }
        public virtual PlayersBlockade PlayersBlockade { get; set; }
        public virtual ICollection<PlayersBlockade> PlayersBlockades { get; set; }
        public virtual ICollection<BlockadeNotification> BlockadeNotifications { get; set; }
        public virtual ICollection<UsersRank> UsersRanks { get; set; }
        public virtual ICollection<UsersRoute> UsersRoutes { get; set; }
        public virtual ICollection<PlayerDiscipline> PlayerDisciplines { get; set; }
        public virtual ICollection<ActivitiesUser> ActivitiesUsers { get; set; }
        public virtual ICollection<ActivityForm> ActivityForms { get; set; }
        public virtual ICollection<ActivityForm> ActivityForms1 { get; set; }
        public virtual ICollection<ActivityFormsSubmittedData> ActivityFormsSubmittedDatas { get; set; }
        public virtual ICollection<ActivityStatusColumnsVisibility> ActivityStatusColumnsVisibilities { get; set; }
        public virtual ICollection<CompetitionRegistration> CompetitionRegistrations { get; set; }
        public virtual ICollection<AdditionalGymnastic> AdditionalGymnastics { get; set; }
        public virtual ICollection<AdditionalTeamGymnastic> AdditionalTeamGymnastics { get; set; }
        public virtual ICollection<TeamScheduleScrapper> TeamScheduleScrappers1 { get; set; }
        public virtual ICollection<UsersEducation> UsersEducations { get; set; }
        public virtual ICollection<DisplayedPaymentMessage> DisplayedPaymentMessages { get; set; }
        public virtual ICollection<NotesMessage> NotesMessages { get; set; }
        public virtual ICollection<SportsRegistration> SportsRegistrations { get; set; }
        public virtual ICollection<PenaltyForExclusion> PenaltyForExclusions { get; set; }
        public virtual ICollection<InitialApprovalDate> InitialApprovalDates { get; set; }
        public virtual ICollection<UsersApprovalDatesHistory> UsersApprovalDatesHistories { get; set; }
        public virtual ICollection<ActivityStatusColumnName> ActivityStatusColumnNames { get; set; }
        public virtual ICollection<ActivityStatusColumnsOrder> ActivityStatusColumnsOrders { get; set; }
        public virtual ICollection<ActivityStatusColumnsSorting> ActivityStatusColumnsSortings { get; set; }
        public virtual ICollection<TennisLeagueGame> TennisLeagueGames { get; set; }
        public virtual ICollection<TennisLeagueGame> TennisLeagueGames1 { get; set; }
        public virtual ICollection<TennisLeagueGame> TennisLeagueGames2 { get; set; }
        public virtual ICollection<TennisLeagueGame> TennisLeagueGames3 { get; set; }
        public virtual ICollection<TennisLeagueGame> TennisLeagueGames21 { get; set; }
        public virtual ICollection<ActivityBranchesState> ActivityBranchesStates { get; set; }
        public virtual ICollection<TennisRank> TennisRanks { get; set; }
        public virtual ICollection<LeagueScheduleState> LeagueScheduleStates { get; set; }
        public virtual ICollection<MedicalCertApprovement> MedicalCertApprovements { get; set; }
        public virtual ICollection<PenaltyForExclusion> PenaltyForExclusions1 { get; set; }
        public virtual ICollection<PlayerHistory> PlayerHistories1 { get; set; }
        public virtual ICollection<PlayersBlockade> PlayersBlockades1 { get; set; }
        public virtual ICollection<TeamsPlayer> TeamsPlayers1 { get; set; }
        public virtual ICollection<UsersApprovalDatesHistory> UsersApprovalDatesHistories1 { get; set; }
        public virtual ICollection<LeaguesFan> LeaguesFans { get; set; }
        public virtual ICollection<ClubBalance> ClubBalances { get; set; }
        public virtual ICollection<CompetitionDisciplineRegistration> CompetitionDisciplineRegistrations { get; set; }
        public virtual ICollection<TeamsRank> TeamsRanks { get; set; }
        public virtual ICollection<TeamsRoute> TeamsRoutes { get; set; }
        public virtual ICollection<RefereeCompetitionRegistration> RefereeCompetitionRegistrations { get; set; }
        public virtual ICollection<RefereeSalaryReport> RefereeSalaryReports { get; set; }
        public virtual ICollection<ResetPasswordRequest> ResetPasswordRequests { get; set; }
        public virtual ICollection<TeamsPlayer> TeamsPlayers2 { get; set; }
        public virtual Auditorium Auditorium { get; set; }
        public virtual ICollection<ActivityFormsSubmittedData> ActivityFormsSubmittedDatas1 { get; set; }
        public virtual ICollection<AthleteNumber> AthleteNumbers { get; set; }
        public virtual ICollection<BicycleFriendshipPayment> BicycleFriendshipPayments { get; set; }
        public virtual ICollection<BicycleDisciplineRegistration> BicycleDisciplineRegistrations { get; set; }
        public virtual ICollection<BicycleFriendshipPayment> DiscardedBicycleFriendshipPayments { get; set; }
        public virtual InsuranceType InsuranceType { get; set; }
        public virtual ICollection<BicycleFriendshipPayment> CreatedBicycleFriendshipPayments { get; set; }
    }
}
