//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public int Id { get; set; }
        public Nullable<int> DriverDetailsId { get; set; }
        public int VehicleLicenseId { get; set; }
        public int VehicleDetailsId { get; set; }
        public int EngineDetailsId { get; set; }
        public int SeasonId { get; set; }
        public int UnionId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual DriverDetail DriverDetail { get; set; }
        public virtual EngineDetail EngineDetail { get; set; }
        public virtual VehicleDetail VehicleDetail { get; set; }
        public virtual VehicleLicens VehicleLicens { get; set; }
        public virtual Season Season { get; set; }
        public virtual Union Union { get; set; }
    }
}
