//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleModel
    {
        public VehicleModel()
        {
            this.VehicleDetails = new HashSet<VehicleDetail>();
            this.VehicleDetails1 = new HashSet<VehicleDetail>();
        }
    
        public int Id { get; set; }
        public int ProductId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<VehicleDetail> VehicleDetails { get; set; }
        public virtual VehicleProduct VehicleProduct { get; set; }
        public virtual ICollection<VehicleDetail> VehicleDetails1 { get; set; }
    }
}
