//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleDetail
    {
        public VehicleDetail()
        {
            this.Vehicles = new HashSet<Vehicle>();
        }
    
        public int Id { get; set; }
        public string Type { get; set; }
        public int ProductId { get; set; }
        public int ModelId { get; set; }
        public System.DateTime YearOfProduction { get; set; }
        public double Weight { get; set; }
        public string ChassisNo { get; set; }
        public int DriverLivenceTypeId { get; set; }
    
        public virtual DriverLicenseType DriverLicenseType { get; set; }
        public virtual VehicleModel VehicleModel { get; set; }
        public virtual VehicleProduct VehicleProduct { get; set; }
        public virtual ICollection<Vehicle> Vehicles { get; set; }
        public virtual VehicleModel VehicleModel1 { get; set; }
    }
}
