//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleLicens
    {
        public VehicleLicens()
        {
            this.Vehicles = new HashSet<Vehicle>();
        }
    
        public int Id { get; set; }
        public string LicenseNumber { get; set; }
        public System.DateTime Valid { get; set; }
    
        public virtual ICollection<Vehicle> Vehicles { get; set; }
    }
}
