//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaterpoloStatistic
    {
        public long Id { get; set; }
        public int GameId { get; set; }
        public int PlayerId { get; set; }
        public Nullable<long> MinutesPlayed { get; set; }
        public Nullable<int> PGOAL { get; set; }
        public Nullable<int> PMISS { get; set; }
        public Nullable<int> AST { get; set; }
        public Nullable<int> STL { get; set; }
        public Nullable<int> BLK { get; set; }
        public Nullable<int> TO { get; set; }
        public Nullable<int> OFFS { get; set; }
        public Nullable<int> FOUL { get; set; }
        public Nullable<int> EXC { get; set; }
        public Nullable<int> BFOUL { get; set; }
        public Nullable<int> SSAVE { get; set; }
        public Nullable<int> YC { get; set; }
        public Nullable<int> RD { get; set; }
        public Nullable<double> EFF { get; set; }
        public Nullable<double> DIFF { get; set; }
        public Nullable<int> TeamId { get; set; }
        public Nullable<int> GOAL { get; set; }
        public Nullable<int> Miss { get; set; }
    
        public virtual GamesCycle GamesCycle { get; set; }
        public virtual TeamsPlayer TeamsPlayer { get; set; }
        public virtual Team Team { get; set; }
    }
}
